### ISSUE TITLE
Failing to get initial value (Vue 3)

### ISSUE THREAD

**Issue by Imperio8** [vueform/multiselect#10]
This is my code. It works just fine, except when "restaurantId" has initial value, it doesn't pre-select the option.

`<restaurant-autocomplete v-model="filters.restaurantId" />` //Int

RestaurantAutocomplete.vue:
```
<template>
    <Multiselect
		    :delay="500"
		    :resolveOnLoad="!!$attrs.modelValue"
		    :options="async (q) => await autocomplete(q)" // [{value: Int, label: String}]
		    :searchable="true"
		    :filterResults="false"
		    :clearOnSearch="true"
		    :clearOnSelect="false"
		    placeholder="Restaurant"
		    :loading="loading"
		    @select="$emit('update:modelValue', $event)"/>
</template>
```

**Comment by adamberecz** [comment]
I don't see `v-model` or `:modelValue` assigned here.

**Comment by Imperio8** [comment]
All the attributes passed to the <restaurant-autocomplete v-model="filters.restaurantId" /> get passed to the root element of the child component automatically.

**Comment by Imperio8** [comment]
https://v3.vuejs.org/guide/component-attrs.html#attribute-inheritance

**Comment by adamberecz** [comment]
But can you actually see Multiselect's `modelValue` prop being set? I don't think so because attribute inheritance works with non-prop attributes and `:modelValue` is a prop. So adding `:modelValue="modelValue"` to multiselect should solve the problem.

Btw generally if you have `resolveOnLoad` set to `true` and the resulting async option list contains an item which `value` equals to the initially set `modelValue` it will be selected once the async process finishes.

**Comment by Imperio8** [comment]
> But can you actually see Multiselect's `modelValue` prop being set? I don't think so because attribute inheritance works with non-prop attributes and `:modelValue` is a prop. So adding `:modelValue="modelValue"` to multiselect should solve the problem.

I tried that. Still doesn't work.

**Comment by Imperio8** [comment]
> Btw generally if you have `resolveOnLoad` set to `true` and the resulting async option list contains an item which `value` equals to the initially set `modelValue` it will be selected once the async process finishes.

The options list get's indeed resolved and I get a list with only one item (my item), it's just not selected.

Btw, myabe this will help you to better understand my usecase. I am getting "this.filters.restaurantId" from this.$route.query, on mounted().

**Comment by Imperio8** [comment]
The error was mine on the binding from the query params. I apologise for wasting your time and thank you for your work.

**Comment by microjafar** [comment]
I used `:model-value="default_value"` that's worked for me in Vue 3
