### ISSUE TITLE
Uncaught TypeError: o.value is not a function

### ISSUE THREAD

**Issue by andresespinosapc** [vueform/multiselect#102]
### Version

* Vue version: 3

### Description

When setting the delay prop, after selecting an option I get `Uncaught TypeError: o.value is not a function`. In the source code the error is here: https://github.com/vueform/multiselect/blob/242aff3ee9238daa78498460480c8d59ed368e53/src/composables/useOptions.js#L418

I don't know if it breaks anything.

### Demo

I don't know why I couldn't reproduce it in JSFiddle, but with this minimal example you should be able to reproduce it:

```javascript
<multiselect
  :options="['option1', 'option2']"
  :delay="300"
/>
```

**Comment by andresespinosapc** [comment]
It seems to be fixed in 2.1.0, that's why I couldn't reproduce it in the JSFiddle

**Comment by Glideh** [comment]
I finally found my issue, I was using a computed instead of a method with the `options` callback

**Comment by caio-2k** [comment]
> I finally found my issue, I was using a computed instead of a method with the `options` callback. The error might need to be caught and explained though.

can you explain how you do it pls ? im having the same error =/

**Comment by Glideh** [comment]
Your `options` prop is set with a `data` ? a `computed` ? or a `method` ?

**Comment by caio-2k** [comment]
> Your `options` prop is set with a `data` ? a `computed` ? or a `method` ?

With a method. I have a method called fetchStates that return a list of items (using axios) like this:

` return states.map((t) => t.name.toUpperCase())`

**states** = store my array of states

The problems is: I cant filter multiselect using :searchable="true", it only shows the list of states

**Comment by caio-2k** [comment]
> > Your `options` prop is set with a `data` ? a `computed` ? or a `method` ?
> 
> With a method. I have a method called fetchStates that return a list of items (using axios) like this:
> 
> ` return states.map((t) => t.name.toUpperCase())`
> 
> **states** = store my array of states
> 
> The problems is: I cant filter (typing in input) multiselect using :searchable="true", it only shows the list of states

Nvm, I have found my problem! 

I forgot to put a properly v-model in multiselect component and **:track-by="'name'"**, that is why nothing is filtered when typing.
