### ISSUE TITLE
Search bar doesnt disappear

### ISSUE THREAD

**Issue by adrieneird** [vueform/multiselect#103]
### Version

* Vue version: 3
* Multiselect version: 2.1.0

### Description

Write something in the search input, close the multiselect (either by selecting something or not)
multiselect-search's modelValue doesn't empty itself; whether you select an option or you just close the multiselect.

### Expected behavior

when you exit the multiselect, multiselect-search's modelValue empties itself.

### Demo

![image](https://user-images.githubusercontent.com/37541112/128328367-eaff2325-f5a4-4af5-a70e-05d007a47ccc.png)

https://jsfiddle.net/ep8a5zdc/

**Comment by Libertie** [comment]
This was previously discussed in Issue #99 and while there is a potential work around there, I agree that this is a bug that should be fixed.

**Comment by adamberecz** [comment]
Fixed in `2.1.1` - thanks for the report
