### ISSUE TITLE
Add tag on blur

### ISSUE THREAD

**Issue by mfanselmo** [vueform/multiselect#104]
Hi!
I would like to ask for the feature of adding a tag when you blur the input? Working in the same way as ` :add-tag-on="['enter', ';', ',', 'blur']"`

I tried implementing it myself with an eventListener on the input blur event, but was not able to make the input clear after the tag was added.

**Comment by adamberecz** [comment]
You might implement this on your own, I don't plan to add it as a core feature. You can use `clearSearch` method for clearing the search field upon adding tag on blur.
