### ISSUE TITLE
Searchable doesn't clear after @select in 2.1.0

### ISSUE THREAD

**Issue by raimondslindezutzu** [vueform/multiselect#106]
### Version

* Vue version: 3

### Description

Searchable doesn't clear search after @select in 2.1.0, this wasn't the issue in 2.0.1

### Demo

https://jsfiddle.net/69m0xde2/

*type f and select "five"*

**Comment by TapanM** [comment]
This was previously discussed in Issue #99 and while there is a potential work around there, I agree that this is a bug that should be fixed.

**Comment by adamberecz** [comment]
Fixed in `2.1.1`
