### ISSUE TITLE
Unable to close dropdown after select

### ISSUE THREAD

**Issue by Imperio8** [vueform/multiselect#11]
If :object="true" the dropdown doesn't close after selecting an option. This might be intended for mode="multiselect", but it happens also for single select.

**Comment by adamberecz** [comment]
It only does not after you **deselect** the option in single select mode (which is the intended behavior). If you experience otherwise please create a [fiddle](https://jsfiddle.net/wLxfv2p5/) that reproduces this because I wasn't able to.

**Comment by vincent-lu** [comment]
Hi @adamberecz any chance to add an option to not open the select dropdown at all when **deselect**?

**Comment by Imperio8** [comment]
The issue was the id. We should provide an id when we have multiple selects in the same view.
