### ISSUE TITLE
Disabling chrome's autofill

### ISSUE THREAD

**Issue by afduarte** [vueform/multiselect#111]
I'm running into a problem where chrome thinks my field is an address field and tries to show a list of values to fill it.

Apparently we can disable this by setting `autocomplete="off"` ([see this](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill)) on the input, but because I have no direct control over the input I can't do this.

Is there a way of doing this through the plugin options/ props? I've gone over the docs and can't seem to find one.

**Comment by adamberecz** [comment]
Added `autocomplete` prop in `2.2.0`.
