### ISSUE TITLE
Can I custom search query with regex ?

### ISSUE THREAD

**Issue by Techit-Kakaew** [vueform/multiselect#114]

**Comment by adamberecz** [comment]
You can set `filterResults` to `false` and use async options to do manual filtering.

**Comment by Techit-Kakaew** [comment]
I mean that I want to custom search query with my regex e.g. user can't search on input some special character such as #$!- 
or can I set new search on input with myself before your component emit ?

for example:
`@search-change="setToSearchInputInYourComponent= $event.replace(/[#$!-]/g, '')"`

**Comment by Techit-Kakaew** [comment]
> You can set `filterResults` to `false` and use async options to do manual filtering.

I mean that I want to custom search query with my regex e.g. user can't search on input some special character such as #$!-
or can I set new search on input with myself ?
or I think that I need search model value that I can custom it

for example:
v-model:search="query"
@search-change="query= $event.replace(/[#$!-]/g, '')"
