### ISSUE TITLE
Empty dropdown showing while async search

### ISSUE THREAD

**Issue by RomanSarvarov** [vueform/multiselect#115]
### Version

* Vue version: 3

### Description

I use layout that have separated dropdown block (margin-top).
So, if I search something with closeOnSearch="true" I have ugly empty div.
Is it possible to hide it while search is going?
On default multiselect styles (even tailwind) that div is showing too - it have ~2px, but I can see it.

By the way - version 2.1.0 and lower does not have this problem.

![Screenshot_2](https://user-images.githubusercontent.com/27378369/130327608-7a86628b-5cae-49a7-ba32-33b9df0b2ad8.jpg)

Jsfiddle: 
I made practical example with big border-width to show you that problem (start typing in search box).
https://jsfiddle.net/rom4i/evLky132/

**Comment by adamberecz** [comment]
Thanks for reporting. Fixed in `2.2.0`.
