### ISSUE TITLE
How can I create multiple tags with the same word? 

### ISSUE THREAD

**Issue by DolphaGo** [vueform/multiselect#119]
I'm using Multiselect like this.
[Tags with search, tags create with no options]
```vue
        <Multiselect
            v-model="mydata.mylist"
            mode="tags"
            placeholder="enter words"
            multiplelabel
            :searchable="true"
            :create-tag="true"
            :showOptions="false"
        />
```

For example, when i typed "aaa", it works. but when i typed "Aaa" right after, it doesn't works.
I think it would have validation for same words.

I want to add ["aaa", "Aaa"] to mylist, but it doesn't works.
How can i solve this?

**Comment by adamberecz** [comment]
Fixed in `2.2.0`.
