### ISSUE TITLE
Return values, not keys

### ISSUE THREAD

**Issue by bugsel** [vueform/multiselect#12]
Is it possible to get the selected values as ['kia', 'mazda'] and not [1, 2] as it is now?

options: ['ford', 'kia', 'mazda'] and mode is tags

**Comment by adamberecz** [comment]
You can do that by providing `options` as an object or an array of objects which have the same values as labels:

```js
options: {
  ford: 'ford',
  kia: 'kia',
  mazda: 'mazda',
}
```

or 

```js
options: [
  { value: 'ford', label: 'ford' },
  { value: 'kia', label: 'kia' },
  { value: 'mazda', label: 'mazda' },
]
```

**Comment by bugsel** [comment]
Thanks Adam,
but if I only have lists as input, means to make a transformation in each control?

`			<Multiselect
				mode="tags"
				v-model="state.resource"
				:options="state.items.map((item) => {
					return {value: item, label: item}
				})"
				:object="false"
			/>`

**Comment by adamberecz** [comment]
Yes, exactly

**Comment by bugsel** [comment]
ok. thanks
