### ISSUE TITLE
Request: Nested options?

### ISSUE THREAD

**Issue by jamols09** [vueform/multiselect#120]
Would like a request to have a feature with nested option or a grouping of optionswould also be nice.

**Comment by adamberecz** [comment]
Added in `2.2.0`:
https://github.com/vueform/multiselect#multiselect-with-groups

**Comment by jamols09** [comment]
Hello @adamberecz , I think this only works for 1st level grouping. What I am referring to is, deeply nested groups .
Lets say for example.
```
option1 
  -group1
    -item1
    -item2
  -group2
    -item12
    -item3
option2
  (...)
```

**Comment by tfdbloom** [comment]
@adamberecz I'm looking for this option as well. It would be a killer component if it had the option. It's been a year, do you have any plans on doing this?

**Comment by stuartcusackie** [comment]
I am also interested in simple [optgroup](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup) functionality - I don't necessarily need multi-level nesting. At the moment it seems clicking on a group selects all items in the group, which is not useful in my case.
