### ISSUE TITLE
¿Como mantener las opciones seleccionadas por defecto?

### ISSUE THREAD

**Issue by GenaroHV** [vueform/multiselect#122]
Si al momento de querer editar un registro que tiene una lista de opciones como lo siguiente:
`{
  name: 'rol1',
  permissions: [
  {
    "id": 1,
    "name": "crear:usuario"
  },
  {
    "id": 2,
    "name": "editar:usuario"
  }
]
}`
Deseo saber cómo o cual es la forma de poder establecer seleccionado por defecto a mi grupo de permisos
`
<input v-model="form.name"/>
<Multiselect
   placeholder="Selecciona una o más"
   v-model="form.permissions"
   label="value"
   mode="tags"
  :options="permissions"/>`

Gracias de antemano.

**Comment by adamberecz** [comment]
To have a default value you just need to set the value of `form.permissions` to a valid option value.
