### ISSUE TITLE
addTagOn triggers on russian «б» character because its the same key on keyboard

### ISSUE THREAD

**Issue by Grawl** [vueform/multiselect#125]
### Version

* Vue version: 3

### Description

I want to add tags with comma character: `,`

I add it to `addTagOn` property of `<Multiselect>` component

```
:add-tag-on=`['enter', ',']`
```

And it works,

**but**

when I write in Russian locale, I cannot type character «б» because it adds tag instead of typing the character

its the same key on my keyboard:

![image](https://user-images.githubusercontent.com/846774/133149796-a65c8665-d210-4213-9b06-ba16da3834d2.png)

**Comment by Grawl** [comment]
It's because `,` and `б` has the same `188` `keyCode` in `keyup` event. But different `key` field.

Multiselect uses `switch` by `keyCode` in `handleKeydown` function:

https://github.com/vueform/multiselect/blob/main/src/composables/useKeyboard.js#L37

I think it should switch by `key` string which more specific

**Comment by Grawl** [comment]
🤦‍♂️

**Comment by adamberecz** [comment]
Got fixed in `2.3.0` with your proposal, which also needed a follow up with tests. Thanks for the effort anyways!

> 🤦‍♂️

Please keep it cool, I'm doing my best.

**Comment by Grawl** [comment]
it was my reaction to bot actions, not your work. VueForm is good OSS anyway
