### ISSUE TITLE
Classes prop doesn't respond to changes when computed

### ISSUE THREAD

**Issue by stevebauman** [vueform/multiselect#126]
### Version

* Vue version: 3

### Description

First off, thanks for the work on this! I really like this select component ❤️ 

When providing the `classes` prop as a computed property, multiselect doesn't apply the changes (i.e. is not reactive to the change).

I'm struggling attempting to apply "invalid" styling to the element, since the component doesn't re-compute class name changes.

### Demo

https://jsfiddle.net/phuqkv0b/

When changing `invalid` to `true` and re-running the fiddle, the text and container border is appropriately changed to red. However, changing it dynamically via a button (for example) does not update the classes and reflect the necessary class changes.

**Comment by adamberecz** [comment]
Thanks for reporting @stevebauman - classes were indeed not reactive. This got fixed in `2.3.0`.

**Comment by stevebauman** [comment]
Thanks @adamberecz! Really appreciate it 🙏
