### ISSUE TITLE
API section in readme.md is wrong in select() and deselect() methods

### ISSUE THREAD

**Issue by Grawl** [vueform/multiselect#130]
In API section of Readme, I see this:

> | Name | Params | Description |
> | --- | --- | --- |
> | **select** | `value`, `option` | Selects an option based on its value. |
> | **deselect** | `value`, `option` | Deselects an option based on its value. |
> | **remove** | `value`, `option` | Alias for `deselect`. |

https://github.com/vueform/multiselect/blame/main/README.md#L231

But in sources, there is only one parameter for each one:

https://github.com/vueform/multiselect/blob/82dfdb0c7917aa43d61360e3673f75f14f4b1b5e/src/composables/useOptions.js#L164

https://github.com/vueform/multiselect/blob/82dfdb0c7917aa43d61360e3673f75f14f4b1b5e/src/composables/useOptions.js#L183

https://github.com/vueform/multiselect/blob/82dfdb0c7917aa43d61360e3673f75f14f4b1b5e/src/composables/useOptions.js#L209

**Comment by adamberecz** [comment]
Updated, thanks.
