### ISSUE TITLE
Can I set new search query on input with myself

### ISSUE THREAD

**Issue by Techit-Kakaew** [vueform/multiselect#131]
I mean that I want to custom search query with my regex e.g. user can't search on input some special character such as #$!-
or can I set new search on input with myself ?
or I think that I need search model value that I can custom it

for example:
`v-model:search="query"`
`@search-change="query= $event.replace(/[#$!-]/g, '')"`

**Comment by adamberecz** [comment]
You might set the value of `.search` programmatically:

``` vue
<template>
  <Multiselect ... ref="multiselect" />
</template>

<script>
export default {
  // ...,
  mounted() {
    this.$refs.multiselect.search = 'value' // In Vue 3 you might use ref in setup
  }
}
</script>
```

**Comment by Techit-Kakaew** [comment]
> You might set the value of `.search` programmatically:
> 
> ```
> <template>
>   <Multiselect ... ref="multiselect" />
> </template>
> 
> <script>
> export default {
>   // ...,
>   mounted() {
>     this.$refs.multiselect.search = 'value' // In Vue 3 you might use ref in setup
>   }
> }
> </script>
> ```

Thanks bro.

**Comment by Techit-Kakaew** [comment]
> > You might set the value of `.search` programmatically:
> > ```
> > <template>
> >   <Multiselect ... ref="multiselect" />
> > </template>
> > 
> > <script>
> > export default {
> >   // ...,
> >   mounted() {
> >     this.$refs.multiselect.search = 'value' // In Vue 3 you might use ref in setup
> >   }
> > }
> > </script>
> > ```
> 
> Thanks bro.

and this in vue 3
const multiselect = ref(null)
`const searchQuery = (value) => {
   multiselect.value.search = query.replace(/[#$!-]/g, '')
}`
