### ISSUE TITLE
Search Inputs Incorrectly Styled When Using TailwindCSS/Forms

### ISSUE THREAD

**Issue by Libertie** [vueform/multiselect#134]
### Version

* Vue version: 3

### Description

When using this library in conjunction with @tailwindcss/forms, the search inputs are being styled with a blue ring outline. This is because the Tailwind plugin ["doesn't use outline for the default focus style, it's a ring + border"](https://github.com/tailwindlabs/tailwindcss-forms/issues/78). But the multiselect `search` and `tagSearch` classes receive `outline-none` and not `focus:ring-0`. The solution is to add `focus:ring-0` to the tailwind stylesheet.

### Demo

![image](https://user-images.githubusercontent.com/745156/133644840-ecfb6d74-98f3-452f-a99c-84c8a58a0764.png)

**Comment by adamberecz** [comment]
Fixed in `2.3.0` based on your solution. Thanks for taking the effort @Libertie !
