### ISSUE TITLE
All tags disappearing when there are multiple Multiselect

### ISSUE THREAD

**Issue by jamols09** [vueform/multiselect#137]
### Version

* Vue version: 3

### Description

I have multiple multiselect that is stored as array if I remove 1 multi select the tags on the other selects gets removed also. Not quite familiar with the jsfiddle thing but I will send a demo link. Please consider this request.

```javascript
<script>
const productVariantOpt = ref([{ value: 'small', label: 'Small' }])
const dynamicField = reactive<[{ attribute: string; value: string[] }]>([
  {
    attribute: '',
    value: [''],
  },
])
const removeAttribute = (e: number) => {
  dynamicField.splice(e, 1)
}
const addAttribute = () => {
    dynamicField.push({ attribute: '', value: [''] })
}
</script>
```
```html
<template v-for="(field, index) in dynamicField" :key="index">
  <Multiselect
    v-model="dynamicField[index].value"
    mode="tags"
    :close-on-select="false"
    :searchable="true"
    :create-tag="true"
    :options="productVariantOpt"
  />
  <button @click="addAttribute">Add</button>
  <button @click="removeAttribute(index)">button</button>
</template>
```

### Demo

https://drive.google.com/file/d/1Tbl2O9ZtginJ8-WFg8uO1BRNXo-gkKs8/view?usp=sharing

**Comment by adamberecz** [comment]
Couldn't debug. Feel free to reopen with a reproducible jsfiddle example. To do that:
- take this bolierplate: https://jsfiddle.net/g56vfpe4/
- recreate your issue and make sure it produces the bug (by hitting Run after modifying the code)
- if you are ready hit Save and send the new url here.
