### ISSUE TITLE
Dropdown border radius is broken

### ISSUE THREAD

**Issue by jbroutier** [vueform/multiselect#139]
The border radius does not applies to the bottom right corner of the dropdown, using the default theme and setting the radius with the `--ms-dropdown-radius` variable.

![missing-radius](https://user-images.githubusercontent.com/36995639/133979990-daabdcb9-cb15-416e-a327-e813e567cfaf.png)

Demo: https://jsfiddle.net/wbt38o0p/
Tested with Firefox 92.0 running on Ubuntu 20.04.

**Comment by adamberecz** [comment]
This should be fixed in `2.3.0` - thank you for reporting @jbroutier.
