### ISSUE TITLE
canDeselect in single mode still able to deselect

### ISSUE THREAD

**Issue by leifcr** [vueform/multiselect#145]
### Version

* Vue version: 3
* Multiselect: 2.2.0

### Description

In single mode, I expected canDeselect to fully disable the option to be able to deselect when setting canDeselect to false.

I expected the deselect (cross) to be gone:
![image](https://user-images.githubusercontent.com/421391/135409370-5bb5ca1f-dc79-4abb-b916-3b13c7d34407.png)

### Demo

https://jsfiddle.net/6jyxw5eb/1/

I changed the initial demo to have canDeselect on the first example. I tried both as a prop, and as an option in the js.

**Comment by adamberecz** [comment]
The `canDeselect` only refers to the ability to select/deselect options from the list. If you want to disable clearing you have to explicitly set `canClear: false`.

**Comment by leifcr** [comment]
thanks @adamberecz

Updated fiddle that works here: https://jsfiddle.net/4kwh0dag/1/
