### ISSUE TITLE
Unit Test with Jest

### ISSUE THREAD

**Issue by Xeyos88** [vueform/multiselect#149]
Hello,
when i try to run unit tests with jest where i include multiselect i get this error:

Cannot use import statement outside a module.

Any suggest?

**Comment by karmenkoh** [comment]
> Hello, when i try to run unit tests with jest where i include multiselect i get this error:
> 
> Cannot use import statement outside a module.
> 
> Any suggest?

i get the same error too

**Comment by Xeyos88** [comment]
> > Hello, when i try to run unit tests with jest where i include multiselect i get this error:
> > Cannot use import statement outside a module.
> > Any suggest?
> 
> i get the same error too

This worked for me:
`jest.mock('@vueform/multiselect', () => {
    return jest.fn()
})`
But obviously then everything concerning the multiselect component must be mocked

**Comment by sthuber90** [comment]
With vue-cli the recommendation seems to be to adjust the [`transformIgnorePatterns`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-jest/README.md#transform-dependencies-from-node_modules) in your _jest.config.js_ file.

```js
module.exports = {
	// ...
	transformIgnorePatterns: ["/node_modules/(?!@vueform/multiselect)"],
}
```

This way testing the multiselect with [testing-library/vue](https://github.com/testing-library/vue-testing-library) works.
