### ISSUE TITLE
Append new option in single mode

### ISSUE THREAD

**Issue by Glideh** [vueform/multiselect#150]
I was expecting to be able add new options in single mode but it doesn't seem to do it

```vue
<Multiselect
  v-model="value"
  :searchable="true"
  :createTag="true"
  :options="options"
/>
```

```js
const appConf = {
  data: () => ({
    value: null,
    options: [
      { value: 'batman', label: 'Batman' },
      { value: 'robin', label: 'Robin' },
      { value: 'joker', label: 'Joker' },
    ],
  })
}
```

Here if I type "Moonnight" then [Enter] I can see `value` is now `{ value: 'Moonnight', label: 'Moonnight }` but not getting added on `options`.

Am I missing something ?

**Comment by Glideh** [comment]
Here is my workaround for now:

```vue
<Multiselect
  v-model="value"
  :searchable="true"
  :createTag="true"
  :options="options"
  @select="select"
/>
```

```js
const appConf = {
  data: () => ({
    value: null,
    options: [
      { value: 'batman', label: 'Batman' },
      { value: 'robin', label: 'Robin' },
      { value: 'joker', label: 'Joker' },
    ],
  }),
  methods: {
    select(optionLabel) {
      if (this.options.find(option => option.label === optionLabel)) return;
      this.options.push({ id: optionLabel, label: optionLabel });
    }
  }
}
```

**Comment by jamols09** [comment]
Gotta ask is this related to this? https://github.com/vueform/multiselect/issues/152

**Comment by Glideh** [comment]
Seems not related, I'm talking about the `single` mode here

**Comment by adamberecz** [comment]
I haven't thought that this would be useful for non-tag inputs. Apparently it is so I've added support for it in `2.3.0` as @Glideh proposed:
* `appendNewTag` -> `appendNewOption`
* `createTag` -> `createOption`
* `addTagOn` -> `addOptionOn`
* `@tag` -> `@option`.

Old options & event will still work but new versions are encouraged from now on. Please report if you encounter any issues as this was a quite big change and even though everything seems to pass I not sure if I managed to think through all real life cases. Closing this for now.
