### ISSUE TITLE
dropdown is not showing

### ISSUE THREAD

**Issue by karmenkoh** [vueform/multiselect#151]
I'm using vue3. Why does it show in a list instead of showing the dropdown select form?

![image](https://user-images.githubusercontent.com/67628612/136049036-be517ee9-ad22-4671-962e-f0256848b8c9.png)

**Comment by adamberecz** [comment]
It seems like you don't have styles included. Here's a possible way to included default styles:

```vue
<template>
  <!-- ... -->
</template>

<script>
  // ...
</script>

<style src="@vueform/multiselect/themes/default.css"></style>
```
