### ISSUE TITLE
refreshOptions example

### ISSUE THREAD

**Issue by picks44** [vueform/multiselect#153]
I'm trying to use the refreshOptions API method, but I don't find out how to use it.
Coudl we have an example in the doc please ?

Thanks.

**Comment by adamberecz** [comment]
Here's a section in our readme on using API methods:
https://github.com/vueform/multiselect#api

Here's a simple example:

```vue
<template>
  <Multiselect
    v-model="value"
    :options="options"
    ref="select"
  />
<template>

<script>
import axios from 'axios'

export default {
  data() {
    return {
      value: null,
      options: async function (query) {
        return await (axios.get('/uri/to/data?query=' + query)).data
      }
    }
  },
  mounted() {
    // this will re-fetch the option list
    this.$refs.select.refreshOptions()
  }
}
</script>
```

Feel free to reopen and specify further what you want to achieve if you still need help.
