### ISSUE TITLE
async options : loader is not stopping if we start typing & click outside

### ISSUE THREAD

**Issue by farisnceit** [vueform/multiselect#156]
### Version

* Vue version: 3

### Description

multiselect - Tags with async options

issue #1 - loader is not stopping if we start typing & click outside

issue #2 - in async options if we gave max option as 1 we are able to search again 

![image](https://user-images.githubusercontent.com/17798473/137675012-bf4fc3fc-cfde-48d3-b6d2-522ad9b66505.png)

![image](https://user-images.githubusercontent.com/17798473/137676236-90868317-91de-47ea-8d94-fbb95f3972f2.png)

### Demo

#7 - Tags with async options -  your Demo fiddle

https://jsfiddle.net/4q3oauy6/6/

**Comment by adamberecz** [comment]
Thanks for reporting @farisnceit - the first part is fixed in `2.3.0`. I'm not sure about what you mean by the second one though. Please reopen if you experience any issues and give some more details.
