### ISSUE TITLE
Single Select with long option selected is breaking on small screens

### ISSUE THREAD

**Issue by farisnceit** [vueform/multiselect#157]
### Version

* Vue version: 3

### Description

when using single select, choosing option with long text with small width is breaking the design

![image](https://user-images.githubusercontent.com/17798473/138029648-bc0339aa-da4d-4564-8e36-c3f311c69584.png)

### Demo

https://jsfiddle.net/w6ktg1vr/2/

**Comment by adamberecz** [comment]
Thanks for reporting @farisnceit - fixed in `2.3.0`.
