### ISSUE TITLE
Changing data is not reflected with options

### ISSUE THREAD

**Issue by diego-betto** [vueform/multiselect#16]
Hi,

it seems that if you change options accessing data directly, rendered options are not updated.
What I'm missing?

Here an example: after 3 seconds options inside data are changed (check console) but options in the select are not regenerated.

https://jsfiddle.net/ex3ntia/vLdfetq7/6/

Thank you

**Comment by diego-betto** [comment]
ok it seems that it loses the reference if you try to assign a new array directly.
In this example after 6 seconds I remove all items from the options array and then push new content.
It works.

https://jsfiddle.net/ex3ntia/vLdfetq7/9/

**Comment by adamberecz** [comment]
Now it should work when you replace `:options` property not alternating it. Please update to `1.2.5`

**Comment by diego-betto** [comment]
Tnx!
