### ISSUE TITLE
Using :value does not set initial value

### ISSUE THREAD

**Issue by mwargan** [vueform/multiselect#160]
### Version

* Vue version: 3

### Description

:value fails to set the initial value on the component. Considering v-model is sugar-syntax for :value and @input, I'd expect :value to work.

### Demo

Please use our [JSFiddle template](https://jsfiddle.net/g56vfpe4/) to reproduce the bug. Issues without working reproduction might be ignored.

^^^ In the demo, change the first example from v-model to a :value like 1 or 2.

**Comment by cogor** [comment]
@mwargan Replace `:value` with `:model-value`
https://v3.vuejs.org/guide/migration/v-model.html
