### ISSUE TITLE
Dropdown does not close

### ISSUE THREAD

**Issue by supermetrolog** [vueform/multiselect#162]
Why does the dropdown not close when clicking on it again like the native dropdown?

**Comment by KaloyanYosifov** [comment]
@adamberecz Do you have time to update this?

**Comment by adamberecz** [comment]
It's a bit tricky with all the different things in the multiselect container (label, placeholder, search, tags, etc). But I'll look into it when I'll have the time.

**Comment by harmnot** [comment]
you can use `ref` for this, @supermetrolog @KaloyanYosifov @adamberecz 
```
<template>
  <multiselect @click="clickMe" ref="multiselect" v-model="inputValue" v-bind="$attrs" />
</template> 



  export default {
   data() {
    return {
      open: false,
    }
   },
   methods: {
    clickMe() {
        this.open = !this.open
        if(!this.open) {
           this.$multiselect.close()
        } else {
           this.$multiselect.open()
        }
     }
   }
  }
```

**Comment by adamberecz** [comment]
I can hardly believe this myself but now it's closing on the second click! Thanks for keeping up guys [🙏](https://emojipedia.org/folded-hands/)
