### ISSUE TITLE
Lost focus on tag adding

### ISSUE THREAD

**Issue by bouffekai** [vueform/multiselect#163]
Hello,

I have a Multiselect component : 
`<Multiselect
    v-model="datas.name.data"
    mode="tags"
    :search="true"
    :searchable="true"
    :placeholder="datas.name.placeholder"
    @open="filteredName"
    :options="datas.name.items"
    track-by="value"
    class="custom-tags-input no-caret"
    :limit="limit"
    :loading="loadingName"
    :disabled="loadingName"
    :showOptions="datas.name.showOptions"
    @search-change="optionsDisplay"
    @close="onCloseDrugname"
    :strict="false"
/>`

On my local machine, once I select an option on autocomplete, the focus stay on the input. But on my staging environment, it's not (same version of the code in both environment). I have to click again on the input to get the focus.
Do you know what can be at the origin of this bug ? 

Thank you for your help.
Jérémy

**Comment by adamberecz** [comment]
Thanks for reporting @bouffekai  - fixed in `2.3.0`. Now every time you select an option while having search the focus should be placed back to the input.
