### ISSUE TITLE
Custom Tag Color

### ISSUE THREAD

**Issue by RogerKeliu** [vueform/multiselect#164]
It is possible to pass a color variable to options for each tag you are using in order to paint each tag  with a custom color ?
If not, there's a way to achieve that ?

As the example you put on docs, adding a color prop.
 :options="[
    { value: 'batman', label: 'Batman' , color : 'red},
    { value: 'robin', label: 'Robin', color: 'green' },
    { value: 'joker', label: 'Joker', color: 'blue' },
  ]"

**Comment by mauro-gobbi** [comment]
I am also interested in this! :)
