### ISSUE TITLE
Slow dropdown with hundreds of options

### ISSUE THREAD

**Issue by giordanovi** [vueform/multiselect#165]
The dropdown becomes slow in interactions when there are hundreds of options.
How can i solve this issue?

**Comment by Zeeex** [comment]
Option 1 (easy):
You can use "limit: 30" the number of entries to 30, then use "searchable: true" to enable searching, filter out results from local array with the "@search-change" event

Option 2 (hard):
Create virtual scrolling with DOM manipulation within dropdown menu

**Comment by giordanovi** [comment]
Hi,
thanks for your reply.
How can I perform Option 2?


Il giorno ven 19 nov 2021 alle ore 15:45 Zeeex ***@***.***>
ha scritto:

**Comment by adamberecz** [comment]
Duplicate #76.

**Comment by adamberecz** [comment]
Added infinite scroll in `2.4.0`. Here's an example:
https://github.com/vueform/multiselect#load-async-options-from-api-on-open-with-infinite-scroll
