### ISSUE TITLE
Tags are not cleared when options list is updated

### ISSUE THREAD

**Issue by Khirkhoff** [vueform/multiselect#167]
If you have selected a TAG and the options list changes/updates with other values. Then an error is thrown if the "new" options list does not contain the already selected tag: **TypeError: Cannot read properties of undefined (reading 'label')**.

Is it possible to clear all tags when options list is updated.

I'm running vue3 (typescript &vcomposition api) with vuex 4 and the options list is fetched from vuex state and is automatically updated depending on other multiselect options.

Using : **"@vueform/multiselect": "^2.2.0",**

**Comment by Khirkhoff** [comment]
Found a way around it

**Comment by AppEternal** [comment]
I solved this by applying a filter on "modelValue" so it doesn't try selecting missing values.

```
<MultiSelect
    :modelValue="modelValue.filter(n => myOptions.some(e => e.value === n))" 
    mode="tags"
    :options="myOptions"
    @input="$emit('update:modelValue', $event)"
/>
```
