### ISSUE TITLE
Unable to output array of object

### ISSUE THREAD

**Issue by Vs-tev** [vueform/multiselect#17]
Hello and Happy new year.
Probably the solution is very easy  but I just can't make it work.
My problem is
when i trying to use Multiselect with an array of objects from api.

> `.get("/strategy/g")
>         .then((response) => {
>           this.strategies = response.data;
>         })` 

in 'strategies' is stored the data 
the output looks like this:
`[ { "id": 2, "name": "Test one", "user_id": 1, }, { "id": 1, "name": "Test two ", "user_id": 2 } ]`

Now when i try to output this in Multiselect 
                  

> `  <Multiselect
>                      v-model="form.strategy_id"
>                       label="name"
>                       valueProp="id"
>                       trackBy="name"
>                       :searchable="true"
>                       :createTag="true"
>                       :object="true"
>                       :options="strategies"
>                   />`

i get nothing 

I also have tried like this but unfortunately without success

> `<Multiselect
>                      v-model="form.strategy_id"
>                       label="label"
>                       valueProp="value"
>                       trackBy="label"
>                       :searchable="true"
>                       :createTag="true"
>                       :object="true"
>                       :options="strategies.map((item) => {
>             return { value: item.id, label: item.name };
>           })"
>                   />`
> 

Thanks in advance

**Comment by adamberecz** [comment]
This is because of #16 . Fixed in `1.2.5`, please update.
