### ISSUE TITLE
how register as plugin nuxt3?

### ISSUE THREAD

**Issue by andysay** [vueform/multiselect#170]
```
import { defineNuxtPlugin } from "#app";
import  multiselect from "@vueform/multiselect";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(multiselect);
});
```

return [Vue warn]: A plugin must either be a function or an object with an "install" function.

**Comment by adamberecz** [comment]
It's not a plugin, you just need to add it as a component:

```js
import { defineNuxtPlugin } from "#app";
import  multiselect from "@vueform/multiselect";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('multiselect', multiselect);
});
```

(Haven't tried but should work)

**Comment by andysay** [comment]
> It's not a plugin, you just need to add it as a component:
> 
> ```js
> import { defineNuxtPlugin } from "#app";
> import  multiselect from "@vueform/multiselect";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.vueApp.component('multiselect', multiselect);
> });
> ```
> 
> (Haven't tried but should work)

 ERROR  [worker] Multiselect is not defined                                                                                                                               13:15:55
