### ISSUE TITLE
No data initialization

### ISSUE THREAD

**Issue by fercho23** [vueform/multiselect#171]
### Version

* Vue version: 3

### Description

The following case would be when using the "tag" mode with searches, calling an API, in this case only fixed data values are returned for ease of use in the example.
In all cases it works perfectly, only that it does not matter what type of information in elementsDefault is never loaded at the beginning

The following line can be modified:
`elementsSelected: this.elementsDefault ?? [],`
With something like
`elementsSelected: [{value: 'value1', label: 'Label 1'}],`

Without having any result, the select always starts empty.

### Demo

```
<div id="app">
  <Multiselect
    v-model="elementsSelected"
    :loading="elementsLoading"
    mode="tags"
    placeholder="Select Elements"
    :closeOnSelect="false"
    :filterResults="false"
    :minChars="1"
    :resolveOnLoad="false"
    :delay="0"
    :searchable="true"
    :search="true"
    :options="async function(name) {
     return await getElementsByNameFromAPI(name);
    }"
  />
</div>

const app = Vue.createApp({
  props: {
    elementsDefault: {
      type: Array,
      default() {
        return [];
      }
    },
  },
  data: () => ({
    elementsLoading: false,
    elementsSelected: this.elementsDefault ?? [],
  }),
  methods: {
    async getElementsByNameFromAPI(name) {
      let elements = [];
      this.elementsLoading = true;
      
      // This is just to simulate calling an API
      if (name) {
        elements = [
          {value: 'value1', label: 'Label 1'},
          {value: 'value2', label: 'Label 2'},
          {value: 'value3', label: 'Label 3'},      
          {value: 'value4', label: 'Label 4'},
        ];
      }
      
      this.elementsLoading = false;
      return elements;
    }
  },
})

app.component('Multiselect', VueformMultiselect)
app.mount('#app')
```

**Comment by mokone91** [comment]
same story(

**Comment by fercho23** [comment]
@mokone91 could you share your code?
because even if it's not fancy or looks strange lol, but it works, I could use it until this is fixed!

**Comment by adamberecz** [comment]
@fercho23 use `:object="true"` so that your default value will be interpreted an object:
https://jsfiddle.net/g56vfpe4/

Otherwise you can only set primitive default values (eg. `['value1', 'value2']`) which are only **values** and multiselect cannot show them if they are not among the options (doesn't know what label to display).
