### ISSUE TITLE
Adding Buttons in dropdown like Select All, Deselect All.

### ISSUE THREAD

**Issue by umang-gramener** [vueform/multiselect#172]
I tried achieving this with beforelist, but was not able to make the button reactive, i even tried putting as check boxes still nothing worked. 
is there a way we can implement this? or can we get it built in as options?

**Comment by ponochovny** [comment]
For some reason when I click many times this "Select all" button - it doubles 'internalValue', and the length of values doubles, so even the message 'multipleLabelText' increases with the count of values

**Comment by ponochovny** [comment]
Found the solution. When click 'Select all' just execute 'Deselect all' and 'Select all' methods

**Comment by georginklv** [comment]
This how it's suppose to happen with composition api ?
