### ISSUE TITLE
Open icon still presented when show-options is false

### ISSUE THREAD

**Issue by mokone91** [vueform/multiselect#173]
Hi!
Im using multiselect for tags field, and i do not have prefilled options, so i set 'show-options' to false, but open icon still visible(
![image](https://user-images.githubusercontent.com/2384641/145017000-877a3cd4-450d-46be-a4c7-4a14b04e5d08.png)

**Comment by adamberecz** [comment]
Thanks for reporting @mokone91  - fixed in `2.3.0`
