### ISSUE TITLE
feature suggestion: set `trackBy` default from `label` props

### ISSUE THREAD

**Issue by castrix** [vueform/multiselect#175]
first of all, thank you for the component library, I just use the library today and I was confused when I tried to add `searchable="true"` props. Then I trace the problem with reading the source code, turns out that I didn't set the `trackBy` props because I use custom key object. I managed to resolve the problem, my suggestion is to force search by `label` prop if it's not empty

```
// useOptions.js
// line 419
return normalize(option[label.vaue || trackBy.value], strict.value).indexOf(normalize(search.value, strict.value)) !== -1
```

**Comment by adamberecz** [comment]
Thanks for the idea @castrix - added this in `2.3.0`.
