### ISSUE TITLE
 WARN @vueform/multiselect is incorrectly packaged. Please contact the package author to fix.

### ISSUE THREAD

**Issue by andysay** [vueform/multiselect#177]
### Version

3

### Description

 WARN @vueform/multiselect is incorrectly packaged. Please contact the package author to fix.

**Comment by adamberecz** [comment]
Is there any info on when this happens?

**Comment by andysay** [comment]
when vite build project.

**Comment by andysay** [comment]
> Is there any info on when this happens?

when vite build project.

**Comment by andysay** [comment]
> Is there any info on when this happens?

need add exports in package.json
