### ISSUE TITLE
Feature request: use entire object as valueProp when providing an array of objects as options

### ISSUE THREAD

**Issue by abaumg** [vueform/multiselect#180]
When providing an array of objects as `options`, I would like to use the entire selected object as `v-model` value, not just a single property.

**Comment by adamberecz** [comment]
Have you checked `:object` prop?

**Comment by abaumg** [comment]
I checked it during my experiments, but later somehow missed it. Please consider this issue as void, sorry for wasting your time. 🤦

**Comment by rizkhal** [comment]
How to make an option is selected when using `:object="true"` props?
