### ISSUE TITLE
Strange dropdown positioning with Tailwind

### ISSUE THREAD

**Issue by Squix** [vueform/multiselect#184]
Hi, I'm using tailwind 3.08, vue3 and vite.

I have setup everything accordingly, the multiselect is showing : 
![image](https://user-images.githubusercontent.com/6475960/147871882-b6e3ff08-71e4-4a49-9f4a-2b63b78b0136.png)
With this code : 
`<Multiselect
          v-model="formData.wrappingList"
          :options="wrappings"
          mode="tags"
          :searchable="true"
          :groups="true"
          placeholder="Salade, Tomates, Oignons"
/>`

But, when clicking on the select, the dropdown list is hiding everything : 
![image](https://user-images.githubusercontent.com/6475960/147871925-95ae2cad-9746-44f4-8d79-a57122ea511b.png)
I can't even see the search text when using autocomplete.

Adding` openDirection="top"` fixes the strange UI, but the list is still hiding the select box and the search query...
![image](https://user-images.githubusercontent.com/6475960/147871968-97f96176-749e-4004-ad57-f43c57d979b6.png)

Can it be related to tailwind provided scss ?

**Comment by adamberecz** [comment]
I tried to reproduce the issue but I wasn't able to. If it's still in issue please create a reproducible example and I'll look into it.
