### ISSUE TITLE
spinner doesn't respect `loading` prop

### ISSUE THREAD

**Issue by brgrapoc** [vueform/multiselect#186]
### Version

* Vue version: 3

### Description

When `loading` is set to `true`, the spinner is always shown when the multiselect input is focused.

When `loading` is set to `false`. We still continue to show the spinner but it correctly hides after the async operation completes.

The issue seems to be related to this bit of code in `useOptions.js`

```
const busy = computed(() => {
    return loading.value || resolving.value
})
```

A suggestion is to remove `busy` and replace all checks for `busy` with `resolving` instead. Since `loading` is only concerned with showing/hiding a UI element it probably shouldn't be so tightly coupled with `resolving`. The slot for the spinner would then be as follows.

```
<slot v-if="loading && resolving && isActive" name="spinner">
  <span :class="classList.spinner"></span>
</slot>
```

### Demo

https://jsfiddle.net/7smnxuq6/2/

Happy to open a PR if needed. Thanks! 🙂

**Comment by benmwendwa** [comment]
@adamberecz this is still happening. The spinner is always showing for me.
I'm using tailwindcss theme.
