### ISSUE TITLE
Override current value when max 1

### ISSUE THREAD

**Issue by SliiCer** [vueform/multiselect#187]
Hello and thanks for the awesome plugin ^^

I'm wondering if it's a way to override current value when new is selected with `mode: 'tags'` and `max: 1`  ?

For now, i need to clear tag and then re-select new one.

Thanks

**Comment by adamberecz** [comment]
What you need it not `mode: 'tags'` but `mode: 'single'` and a custom `singlelabel` slot styled like a tag. Similar to this but with `singlelabel`:
https://github.com/vueform/multiselect#multiselect-with-custom-label-slot
