### ISSUE TITLE
Removing tags with async options and resolve-on-load enabled

### ISSUE THREAD

**Issue by joakimkm** [vueform/multiselect#196]
### Version

* Vue version: 3

### Description

Bug occurs when "resolve-on-load" is active and tags with async options is enabled.
When dynamically trying to remove tags, either the wrong tags is removed or nothing happens.

I found a hacky solution looping through `this.$refs.multiselect.iv `and using `this.$refs.multiselect.handleTagRemove()`._

### Demo

 [JSFiddle template](https://jsfiddle.net/Ltux7rw3/)

**Comment by adamberecz** [comment]
The problem here @joakimkm is that you're not returning the actual async results when the search is empty. I'd recommend going with `:object="true"` which allows you to have default options even the option list is not loaded:
https://jsfiddle.net/g29q8ub3/
