### ISSUE TITLE
Infinite scroll or an emit from the component when the scroll reached the end so that we can add more data using limit or page from Rest API.

### ISSUE THREAD

**Issue by paul122297** [vueform/multiselect#198]
Infinite scroll or an emit from the component when the scroll reached the end so that we can add more data using limit or page from the Rest API.

**Comment by adamberecz** [comment]
Added infinite scroll in `2.4.0`. Here's an example:
https://github.com/vueform/multiselect#load-async-options-from-api-on-open-with-infinite-scroll
