### ISSUE TITLE
Disabled for options is not possible

### ISSUE THREAD

**Issue by SilberMa** [vueform/multiselect#2]
Hi,

need to disable a few options of a filteredList and still need them to be listed in the dropdown (like crossed out).

I tried with: 
```
[ { "value": "1", "label": "de-AT", "disabled": false }, { "value": "2", "label": "de-CH", "disabled": false }, { "value": "3, "label": "en-GB", "disabled": false }, { "value": "4", "label": "en-CA", "disabled": false }, { "value": "5", "label": "de-DE", "disabled": true }, { "value": "6", "label": "en-US", "disabled": false } ]
```
 as options, but this doesn't really do anything.
 
Is there a possibility to achieve this or is your multiselect designed to display only choosable options?

**Comment by adamberecz** [comment]
This will be available in the next minor release. Hopefully in a couple of days.

**Comment by adamberecz** [comment]
Now this should work in latest release `1.2.0`.
