### ISSUE TITLE
[Feature request] Add disabled-prop, just like value-prop and label

### ISSUE THREAD

**Issue by lllopo** [vueform/multiselect#202]
I have the following case : the objects in the list that is fed to the component contain a property named 'disabled' and this results in that the options in the multiselect become disabled. The thing is, that I want them to be actually enabled and just rendered differently. A workaround is to loop the objects array and change the property name, but this unnecessary overhead could be easily avoided by adding something like "disabled-prop", which works the same way as "value-prop" and "label" properties. In addition - it would be useful in the opposite cases where a list of objects comes with property that means "disabled", but is named differently.

**Comment by antonioferngarcia** [comment]
Same issue, disabled prop is not working and the only way to force multiselect as disable is adding "disabled: true" to every option

**Comment by lllopo** [comment]
Well, stale because no one takes care to at least give some response to this. Sweet.

**Comment by adamberecz** [comment]
Added `disabledProp` in `2.4.0`.
