### ISSUE TITLE
Single select with 'canDeselect=true' does not behave as real select

### ISSUE THREAD

**Issue by lllopo** [vueform/multiselect#203]
### Version

* Vue version: 3

### Description

I have the following multiselect 

`<Multiselect :options="locations" v-model="currentLocation" value-prop="id" label="name" :object="true" :canClear="false" :canDeselect="false"></Multiselect>`

The `locations` property is dynamic and changes externally, BUT I need the select to always have a value (unless `locations` is fully empty, of course). Now, having that there is no empty value in the set and if the currently selected value disappears from the list, what a normal behavior would be is to fall back to the first option in the list (and that is how a simple DOM select would behave). Unfortunately - the Multiselect just comes up empty, which is very wrong having that there is no such option in the list at all while others are available. 
This might be expected behavior in multiselect/tag mode, but certainly not with single select mode. I was hoping that `canDeselect` will fix this behavior, but unfortunately it didn't and I think at least with `canDeselect=true` the first available option should be selected, everything else is counterintuitive.

**Comment by nicoagp** [comment]
Have you tried ? :can-deselect="false"

**Comment by lllopo** [comment]
> Have you tried ? :can-deselect="false"

Yup. No luck.

**Comment by lllopo** [comment]
@adamberecz yes, we do test different behaviors. What you are doing is thinking Vue, which is completely ok, but not suitable for this specific test. What you do in your example is to re-bind options, BUT this actually triggers re-render of the whole element DOM and this is nothing like what happens if you actually remove an option from the list of options, like if you do Node.removeChild() on an option. Then you'll get the real DOM select behavior when you remove a selected option and it is exactly what I'm describing - fall back to the first available. What you do is not a fallback, it is a complete re-render.

As of the common sense arguments -  as I said -  adding an (empty) option and selecting it makes much less sense to me, than selecting an existing one, but on that point - I must admit one is free to have it's own thinking and preferences. Still ... this doesn't change the fact mine matches the native select logic ;-).

**Comment by adamberecz** [comment]
As Multiselect is based on Vue.js I think it's ok to behave as you'd expect in Vue.js environment. But you're right, removing it with native JS does select the first option - I wasn't aware of that.

**Comment by lllopo** [comment]
@adamberecz I won't argue any further, it is up to you as author to decide what-works-how after all. I just think the main goal for such type of components should be to build on top of their DOM counterparts, not alter, as otherwise switching to a different component or reverting to the DOM original would require app logic changes just because of this (and could easily go unnoticed and lead to errors and problems) and this I find to be a bad practice.

**Comment by adamberecz** [comment]
> switching to a different component or reverting to the DOM original would require app logic changes just because of this (and could easily go unnoticed and lead to errors and problems)

My point exactly. But the *original* here is Vue.js not native DOM so switching to native DOM behavior (which Vue.js does not itself) could introduce problems. Rigidly sticking to *"how things should work"* instead of *"how things actually work"* in this case is a bad practice imho, because the end user cares nothing about original DOM behavior in a Vue.js environment (unless they are rewriting a whole app from native HTML + JS to Vue.js + @vueform/multiselect in one step which is think is less common).

On the other hand I agree that things like this should match native behaviour, so reporting it for Vue maintainers would be the first. But I think nobody just ever cared about this enough to make an effort... at least yet.
