### ISSUE TITLE
createOption always creates a tag

### ISSUE THREAD

**Issue by rodrigost23** [vueform/multiselect#204]
The `createOption` attribute allows the user to type something that wasn't found by the search, and `appendNewOption` prevents it from showing in the options list.

The event `@option` fires before the tag is created, but it cannot modify it or prevent it from being created.

---

I wanted to intercept the creation of the tag. So when the user pressed enter or clicked in the option they typed, it would show a modal, have data saved on the backend, then get the id and send it to multiselect.

If I try to do this in the `@option` event, I end up with two tags: the one that was created automatically, and the one I created manually.

A way of *not* creating a tag with `createOption` would be nice, and a way of (asynchronously) creating the tag and the option, would be even better.

**Comment by Bassadin** [comment]
I'm facing the same problem, but I think that's what `appendNewOption` is supposed to be for. It doesn't seem to work, though.

**Comment by Bassadin** [comment]
https://github.com/vueform/multiselect/blob/abb86d6697ae133ff102504f46e63e4ad8c8b598/src/composables/useOptions.js#L394

This if here seems to work as intended, but the options still gets pushed into the selected options/value. Maybe I'll find out some more but I never really worked with a vue component module like this. I'm currently having multiselect open in a separate window and copy over the compiled dist files into my main folder. More development diary entries to follow...

**Comment by Bassadin** [comment]
@vueform I haven't worked on something like this yet but I think this PR might fix the issue @rodrigost23 and I are having. Feel free to criticize me and give me some tips on how to better help develop the multiselect thing. It was a fun and rewarding experience to find this bug :D

**Comment by adamberecz** [comment]
Thanks for the effort @Bassadin, it turned out to be better to add an `onCreate` option that can handle tag creation. Here's a complete example:
https://github.com/vueform/multiselect#manage-created-tag-asynchronously

**Comment by Bassadin** [comment]
@adamberecz Thanks a lot! For something that I hacked together in half an hour at work while having next to no experience with actual development of vue or npm modules, I'm more than happy that I could help at all. Cheers!
