### ISSUE TITLE
Resolve on/before open property

### ISSUE THREAD

**Issue by Gerych1984** [vueform/multiselect#205]
Good day. Thanks for that component and sorry for my bad English. My issue - how resolve async options **before** or **on** open event? I recreate [that fiddle](https://jsfiddle.net/wvaoLupm/3/) and as you can see - first click on component opened empty results list, but second show already loaded results (in real time - results loaded when popup closed). So - can you explain me, how load and show options when result list opened in first time without `resolve-on-load`? I don't want resolve on load because it can be very heavy API or some requests restrict, but user may not use current component. Many thanks

**Comment by ImGelu** [comment]
Having the same problem. The query returns the right results, but they're shown in the select input only after retriggering the focus event. @adamberecz Could you take a look, please? I'm using Vue 3.

**Comment by adamberecz** [comment]
I've added an example for this @Gerych1984:
https://github.com/vueform/multiselect#load-async-options-from-api-on-open-with-infinite-scroll
