### ISSUE TITLE
@vueform/multiselect doesn't appear to be written in CJS - NUXT 3

### ISSUE THREAD

**Issue by shahabbasian** [vueform/multiselect#207]
after build production in NUXT 3

WARN  @vueform/multiselect doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

### Version

* Vue version: 3

**Comment by rajeevfaya** [comment]
Hey, I am not able to add @vueform/multiselect in Nuxt3. can I get any detailed documentation

**Comment by adamberecz** [comment]
@shahabbasian thanks - fixed in `2.4.0`.

@rajeevfaya just follow plain Vue 3 guide: https://github.com/vueform/multiselect#using-with-vue-3
