### ISSUE TITLE
Tags mode ignores v-model (doesn't populate)

### ISSUE THREAD

**Issue by sourcecodeit** [vueform/multiselect#209]
### Version

* Vue version: 3

### Description

Multiselect with tags mode ignores starting value of its v-model and it doesn't update neither.

### Demo

https://codesandbox.io/s/restless-dream-dbuk1p?file=/src/components/HelloWorld.vue

**Comment by AshDavies247** [comment]
I think the items in your modelValue also need to be valid options that you've passed to the same component. In your example, adding an array for "options" that mirrors the tags solves your issue.

**Comment by juanesarango** [comment]
That's a good point @AshDavies247. Do you see any way of achieving this when `options` is an async method? 

For example, using example #7 of the [demo](https://jsfiddle.net/xf0jzoct/), initializing it with `value: ['Python']`

**Comment by adamberecz** [comment]
The values of `v-model` need to be among the `:options` as @AshDavies247 correctly said. Here I wrote about this more:
https://github.com/vueform/multiselect/issues/218#issuecomment-1141454310

Also here are some examples to add default values without having to add them to options:
https://github.com/vueform/multiselect#async-options-with-default-values
https://github.com/vueform/multiselect#default-values-that-are-not-among-the-options
