### ISSUE TITLE
Question: How can I give focus to the input field in an elegant way?

### ISSUE THREAD

**Issue by stefandesu** [vueform/multiselect#21]
I need to programmatically focus the input field. Before, we used a normal `<input>` element and were able to simply `this.$refs.input.focus()`. This is not possible when using multiselect and I couldn't find anything in the docs or code that would allow it.

My current workaround is this:
```js
const input = this.$refs.input.$el.getElementsByTagName("input")[0]
input && input.focus()
```

Is there are more elegant way of solving this? Thanks!

**Comment by adamberecz** [comment]
The `Multiselect` component does have an `input` ref, but you'll need a double `nextTick` if you'd like to access it upon render (first your component is rendered, then multiselect and refs need a tick to be available).

``` js
mounted() {
  nextTick(() => {
    nextTick(() => {
      this.input.input.focus()
    })
  })
}
```

**Comment by stefandesu** [comment]
Thanks! It gets a little more complicated since I'm using a component that wraps around your component, but this is better than what I did before. 👍
