### ISSUE TITLE
Height of .multiselect-dropdown

### ISSUE THREAD

**Issue by jorr-it** [vueform/multiselect#217]
The height of the dropped down list always has a height of 150 pixels, no matter the number of lines. I tried to play with `--ms-max-height` or with code like below, but I can't get it to work with auto height. 

```
.multiselect-dropdown {
    height: auto;
    max-height: 40rem;
}
```

How do I get an adjustive height the best way?

**Comment by adamberecz** [comment]
`--ms-max-height: none;` should solve the problem.
