### ISSUE TITLE
Problems in refresh options selectable?

### ISSUE THREAD

**Issue by Jesus-Rojas** [vueform/multiselect#219]
Vue 3

Good evening, excuse me, I have problems updating the selected options, the initial value is [], then I enter information, the tags appear, but the selectable one is not updated. Some method that is being overlooked. Thanks

![image](https://user-images.githubusercontent.com/57029059/160270604-e867eb5d-d56d-4973-a109-2c75cc5215be.png)
![image](https://user-images.githubusercontent.com/57029059/160270647-d14ce77b-7325-439d-a125-7596fcd30000.png)

**Comment by adamberecz** [comment]
Feel free to reopen this with a reproducible example if you still have the issue.
