### ISSUE TITLE
Q: Any plans for adding accessibility?

### ISSUE THREAD

**Issue by marzena-mks** [vueform/multiselect#22]
Do you have any plans for adding accessibility features to the component in the near future?

**Comment by adamberecz** [comment]
I need to do some research on the topic, but yeah, I've already thought about that.

**Comment by illmatix** [comment]
I'm also looking for this feature.

**Comment by BirdDogJoe** [comment]
You can access the inner input by using a ref.

<Multiselect class="border" v-model="input" mode="tags" ref="multiselect"  />

In your TS code just set the input id to whatever you want the id to be.

mounted() { this.$refs.multiselect.input.id = "myId"; },

Now you have the id set and can use that to associate a label to the multiselect box which will allow non-sight users to use the application. Hope this helps!

**Comment by adamberecz** [comment]
Finally. I did some research and now Multiselect is accessible. I'm not close to the topic but hopefully what I implemented works. Please reopen if you find any issues.
