### ISSUE TITLE
@apply inexistant class

### ISSUE THREAD

**Issue by andrelec1** [vueform/multiselect#220]
Syntax Error: ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(54:2) /node_modules/@vueform/multiselect/themes/tailwind.scss The `bg-multiselect-remove` class does not exist, but `multiselect-tag-remove` does. If you're sure that `bg-multiselect-remove` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  52 | 
  53 | .multiselect-tag-remove-icon {
> 54 |   @apply bg-multiselect-remove bg-center bg-no-repeat opacity-30 inline-block w-3 h-3;
     |  ^
  55 | }
  56 |

**Comment by Drillan767** [comment]
I have the same problem, using version `2.3.3`

The library was freshly installed, then I added the following lines:

```
import Multiselect from '@vueform/multiselect';
import '@vueform/multiselect/themes/tailwind.css';
```

Both `default.css` and `default.scss` are working, but none of the `tailwind` ones.

I hope it gives more context.

**Comment by adamberecz** [comment]
Make sure to add the background images to `tailwind.config.js` (first block):
https://github.com/vueform/multiselect#styling-with-tailwind-css
