### ISSUE TITLE
Single mode - Option with `false` value not correctly displayed when selected

### ISSUE THREAD

**Issue by antoinematyja** [vueform/multiselect#222]
### Version

* Vue version: 3

### Description

In single mode, when an option with a `false` value is selected, it is displayed as if no option is selected.
The v-model gets the `false` value so it's just a display issue.

I looked at the code (btw it's very pleasant to read) and the culprit seems to be https://github.com/vueform/multiselect/blob/main/src/composables/useOptions.js#L124

`hasSelected` will return `false` if the value is "nullish" = `null`/`false`/`undefined`. Instead it should check if the value is the value when nothing is selected (`nullValue` computed?).

### Demo

https://jsfiddle.net/Owumaro/b7hakdct/3/

**Comment by adamberecz** [comment]
Thanks - fixed in `2.4.0`.
