### ISSUE TITLE
spinner is not visible if multiselect is not active

### ISSUE THREAD

**Issue by RomanSarvarov** [vueform/multiselect#223]
### Version

* Vue version: 3

### Description
If multiselect is not active (opened), spinner is not visible even if loading prop is true.
On my app there is async loading after component mounted, and because select is not active users does not see spinner, and that is not UI friendly.

In code I see that spinner is showing when busy && isActive.
Should we remove check for isActive?

**Comment by adamberecz** [comment]
Thanks - fixed in `2.4.0`.
