### ISSUE TITLE
Error in afterlist slot

### ISSUE THREAD

**Issue by antonioferngarcia** [vueform/multiselect#225]
### Version

* Vue version: 3

### Description

* I'm trying to use the slot afterList to show a last item with a loadMore button, but when i use it, this slot is not placed at the end of the list (inside  `<ul>` ) instead is placed after the list and when i open the multiselect to see the options the "load more" is over the select options.

### Demo

* [JSFiddle Demo](https://jsfiddle.net/st18n6ug/2/) to reproduce the bug.

**Comment by v1r0x** [comment]
I have the same problem (also Vue 3).
As a workaround I added `overflow: auto;` to `multiselect-options` css. Now the "normal" options are scrollable and the afterlist slot is rendered as fixed element in the dropdown.
But as you said, it would be better to have it as an element inside the options list

**Comment by adamberecz** [comment]
Thanks guys, fixed in `2.4.0`
