### ISSUE TITLE
:min-chars="0" not work in Release 2.3.4

### ISSUE THREAD

**Issue by jc579** [vueform/multiselect#230]
### Version

* Vue version: 3 

### Description

In the latest release 2.3.4, when the param minChars is set to 0, the options will not be refreshed with an empty query.

`<Multiselect
    ref="multiselect"
    v-model="value"
    mode="tags"
    :filter-results="false"
    :delay="0"
    :min-chars="0"
    :searchable="true"
    :close-on-select="false"
    :options="async function(query) {
      return await fetchOptions(query)
    }"
/>`

P.S. In 2.3.3, it works fine.

### Demo

Please use our [JSFiddle template](https://jsfiddle.net/g56vfpe4/) to reproduce the bug. Issues without working reproduction might be ignored.

**Comment by adamberecz** [comment]
Thanks, fixed in `2.4.0`
