### ISSUE TITLE
How to use ref for multiselect with types and composition-api in Vue 3?

### ISSUE THREAD

**Issue by rezuankassim** [vueform/multiselect#231]
I currently have these codes
```
import Multiselect from '@vueform/multiselect'
...
setup() {
    const multiselect = ref<Multiselect | null>(null)
                            ^^^^^^^^^^^
// Error: Cannot use namespace 'Multiselect' as type
}
```
How do go around and do this? Sorry this is my first time using typescript. Thanks in advance.

**Comment by EShebunin** [comment]
Hi, you can do like this
```const multiselect = ref<InstanceType<typeof MultiSelect>>(null);```

**Comment by cnakh** [comment]
@EShebunin When I access `clear()` or other methods it not works

`Property 'clear' does not exist on type 'Multiselect'`

**Comment by rayanazzam1991** [comment]
I have same issue please help with this

**Comment by xibman** [comment]
@rayanazzam1991  simple workaround:

```ts
interface CustomMultiselect extends Multiselect{
    close: () => void;
    clear: () => void;
  }
  ```

**Comment by adamberecz** [comment]
Could anyone reliably help me with TS issues to put everything in place once and for all in both Vue 2 & 3? If so, please let me know!

**Comment by tienanhbui** [comment]
I have same issue.
I think it not support defineExpose ref for composition-api in Vue 3

**Comment by n14s** [comment]
Same issue, and i think @tienanhbui is right.
Is there any plan on adding this?
Or is there any workaround to access the api methods?

**Comment by adamberecz** [comment]
This should be fixed with the upcoming release. If not, feel free to reopen.
