### ISSUE TITLE
How to validate an Option before appending to the tag list

### ISSUE THREAD

**Issue by Gabrielr47** [vueform/multiselect#232]
Hi, I'm trying to create a multi email input, so each time the users enters a valid email I add as a tag and if is not an email I leave as a text until the users type a valid one, the problem is that I couldn't find a way of intercepting the before create Tag to add this validation, is it possible or I would have to introduce a `beforeCreateTag` method for it?

Demo: 
https://stackblitz.com/edit/vueform-multiselect-multiple-mode-kyj8fh?file=src%2Fcomponents%2FMyComponent.vue

So far the events I tried emit after inserting the tag, I tried @tag and @option, would be nice to have a way of validating before  creating the tag, this way i could paste a list of emails with commas and split into several tags.

**Comment by adamberecz** [comment]
@Gabrielr47 added `onCreate` option in `2.4.0`, here's how you can use it:
https://github.com/vueform/multiselect#manage-created-tag-asynchronously

**Comment by Gabrielr47** [comment]
Ok, I actually don't need the @paste to be able to split into multiple tags, awesome, this is working on single and multiple emails result: 
https://stackblitz.com/edit/vueform-multiselect-multiple-mode-plqtkw?file=src/components/MyComponent.vue
Cheers! 😄
