### ISSUE TITLE
Styles: Repeat styles for multiselect-dropdown

### ISSUE THREAD

**Issue by EShebunin** [vueform/multiselect#240]
### Version

* Vue version: 3

### Description

Hi, on the lines
https://github.com/vueform/multiselect/blob/fc652f690c96323d63919591f5a9e5b6a5a5abf2/themes/default.scss#L289
https://github.com/vueform/multiselect/blob/fc652f690c96323d63919591f5a9e5b6a5a5abf2/themes/default.scss#L298
styles overlap each other. Fix please

### Demo

Please use our [JSFiddle template](https://jsfiddle.net/g56vfpe4/) to reproduce the bug. Issues without working reproduction might be ignored.

**Comment by adamberecz** [comment]
Fixed in `2.5.8`.
