### ISSUE TITLE
Css not loading at all

### ISSUE THREAD

**Issue by luigibriganti** [vueform/multiselect#242]
The component in my template doesn't look like yours. I think css is not been loaded.
Am I missing something? I'm using Vue 3.

![multi](https://user-images.githubusercontent.com/107467952/173537055-1e372504-78f6-46b2-9bec-365d33159333.png)

**Comment by adamberecz** [comment]
Yep, probably you forgot to include CSS:
https://github.com/vueform/multiselect#using-with-vue-3

```html
<style src="@vueform/multiselect/themes/default.css"></style>
```

**Comment by ramieita** [comment]
i have the same issue css are not loaded 

`   
import "@vueform/multiselect/themes/default.css";
import Multiselect from '@vueform/multiselect'; 

export default {
  components: {Multiselect}, 
}

 `


i have tried  also to link the css file like that -> 

<style src="@vueform/multiselect/themes/default.css"></style>

still no css are loaded 


`  "dependencies": {
    "@vue/compiler-sfc": "^3.1.0",
    "@vueform/multiselect": "^2.4.2",
    "vue": "^3.1.0",
    "vue-loader": "^16.8.3",
    "vue-router": "^3.4.9",

  }`
