### ISSUE TITLE
Search problem with norwegian characters Æ and Ø

### ISSUE THREAD

**Issue by AntonSmatanik** [vueform/multiselect#243]
* Vue version: 3
* Package version: latest

### Description

Component doesn't work well with norwegian characters.

When you search for “A“ it does not look for Æ.
When you search for “O“ it does not look for Ø.

Even with strict option set to `false` user is not able to do it.

Is there an easy way how to achieve the desired result?

**Comment by adamberecz** [comment]
Fixed in `2.5.8`.
