### ISSUE TITLE
i got an error after install the library, TypeError: Cannot read property 'value' of undefined (Typescript Vue 3)

### ISSUE THREAD

**Issue by josuastg** [vueform/multiselect#25]
TypeError: Cannot read property 'value' of undefined (Typescript Vue 3)

**Comment by adamberecz** [comment]
It's not compatible with Typescript yet.

**Comment by fvdung** [comment]
I have same problem with javascript not typescript

**Comment by ashafizullah** [comment]
Its also happen with javascript

**Comment by adamberecz** [comment]
> TypeError: Cannot read property 'value' of undefined (Typescript Vue 3)

**Comment by adamberecz** [comment]
> TypeError: Cannot read property 'value' of undefined (Typescript Vue 3)

Could you provide an example?

**Comment by adamberecz** [comment]
> How to use options with data in reactive?

I'm not sure if I understand the question, could you be a bit more specific?

**Comment by adamberecz** [comment]
Closed with resolution from @ashafizullah. If the issue persist feel free to reopen.
