### ISSUE TITLE
Crashes in ESM SSR: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by negezor** [vueform/multiselect#258]
### Version

* Vue version: 3

### Description

`Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

Applying any of the above fixes the problem of my ESM SSR server crashing. I'm using a clean Vite build for SSR.

**Comment by svengt** [comment]
Until this issue is resolved you can fix this by patching the package.json of the module. You can install this patch via [patch-package](https://www.npmjs.com/package/patch-package)

[@vueform+multiselect+2.5.8.patch](https://github.com/vueform/multiselect/files/10794324/%40vueform%2Bmultiselect%2B2.5.8.patch)

**Comment by adamberecz** [comment]
From `2.6.0` the `module` now points to an `.mjs`. Hope this fixes - if not please reopen.

**Comment by svengt** [comment]
@adamberecz I still experience the same problem. Also the temporary fix I posted earlier does not seem to work any more.

```console
(node:260) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/project/node_modules/@vueform/multiselect/dist/multiselect.js:1
import { toRefs, getCurrentInstance, ref, computed, watch, nextTick, onMounted, openBlock, createElementBlock, normalizeClass, createElementVNode, mergeProps, createCommentVNode, w
ithModifiers, Fragment, renderList, renderSlot, withKeys, createTextVNode, toDisplayString } from 'vue';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1119:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
/project/node_modules/@vueform/multiselect/dist/multiselect.js:1
```

**Comment by negezor** [comment]
We have to use [exports](https://nodejs.org/api/packages.html#package-entry-points) in package.json

https://github.com/vuejs/router/blob/c5c191585540e3fec2325a704903d0b5471f26e1/packages/router/package.json#L2-L31

**Comment by adamberecz** [comment]
Released a patch with @negezor's solution. Let's see if it works.

**Comment by negezor** [comment]
@adamberecz Great, this now works in an SSR environment. Thanks for the fix.

A small note, there is no environment difference for
development and production, so this part can be safely removed.
https://github.com/vueform/multiselect/blob/b192b631840cba3c5ad6d92b902ce408e193fd6e/package.json#L17-L28

Can we do the same fix for other vueform modules? For example:
https://github.com/vueform/slider
https://github.com/vueform/toggle
