### ISSUE TITLE
v-model doesnt work both ways

### ISSUE THREAD

**Issue by XiDanko** [vueform/multiselect#263]
multiselect doesnt apply the selected item if the selected item changed from an outside action
it was working before!

**Comment by DavidVaness** [comment]
Yeah I have the same issue rn

**Comment by XiDanko** [comment]
using vue3
i have empty array of options and onMounted i fetch the data from api then set the array
multiselect is v-model is set to empty object which get fetched from api onMounted as well
bot options and v-model object are reactive
i had v2.4.2 and everything is working if i dont update
