### ISSUE TITLE
async loading function called every time a data attribute changed

### ISSUE THREAD

**Issue by andreas83** [vueform/multiselect#266]
### Version

* Vue version: 3
* Nuxt Version:     `3.0.0-rc.11-27722816.abd0feb` 
### Description

Changing any data property triggers the async loading function.
Looks like its somehow related to the resolve-on-load function.

### Demo

https://codesandbox.io/s/quizzical-danny-shgoy0?file=/src/App.vue

**Comment by muhammedkaraoglu** [comment]
@adamberecz  Today I realized that I faced the same problem. When will there be an update for this?
https://codesandbox.io/s/vueform-multiselect-async-loading-function-called-every-time-a-data-attribute-changed-ponmug

**Comment by andreas83** [comment]
@adamberecz could you please review the pull request?

**Comment by andreas83** [comment]
@adamberecz  thank you very much!!!
