### ISSUE TITLE
case 'ArrowLeft': D.value is null

### ISSUE THREAD

**Issue by dvnrsn** [vueform/multiselect#271]
This issue may or may not be helpful to authors of the library and I am not expecting them to solve this per se. I am simply documenting as I experience it and investigate.

Caused by upgrade from 2.5.2 to 2.5.6

**Comment by dvnrsn** [comment]
This is a visual of "tags"

<img width="457" alt="image" src="https://user-images.githubusercontent.com/9112811/193828427-78495d65-6ea3-4c00-aec1-f660aca0fe2e.png">

**Comment by zigomir** [comment]
I can confirm the error comes from [2.5.3](https://github.com/vueform/multiselect/releases/tag/2.5.3)

**Comment by dvnrsn** [comment]
Also observed an issue that may be related

TypeError: Cannot read properties of null (reading 'blur')

**Comment by adamberecz** [comment]
Fixed in `2.5.7`. Thanks for reporting.
