### ISSUE TITLE
Issue repopulating multiselect when value is set to object.

### ISSUE THREAD

**Issue by XPAULUSX** [vueform/multiselect#274]
Version 2.5.6
Vue 3

Hi, i've found an issue when setting the multiselect component up with values which are objects in tag mode.

In my screenshot below you can see, I have a multiselect selected values configured to an object, with "label" being used to display relevant names within the tags.

![image](https://user-images.githubusercontent.com/47896035/195873433-1fdea975-3ded-491a-baf5-d97749449ade.png)

When it comes to repopulating this control using v-model I see the following:

![image](https://user-images.githubusercontent.com/47896035/195874279-2c69cf05-dd8e-49a0-af67-4d7510e61205.png)

Looking at the markup, it looks obvious that the selected values are being used to populate tag id attributes, which is why it fails to  repopulate correctly and is instead,  selecting first in the list each time.

![image](https://user-images.githubusercontent.com/47896035/195875294-b18fc0aa-8464-467f-8db3-84972d1648d7.png)

I'd like to be able to set the value to an object for my project, but understand a refactor may be required my end if this is not desired usability?

Any help appreciated, thanks.

**Comment by adamberecz** [comment]
You can use `object: true`. The display or `id` was fixed in `2.5.7`.
