### ISSUE TITLE
Searching after several scrolls in a drop down list causes the drop down to stick, error and no selection can be made.

### ISSUE THREAD

**Issue by thefunvampire** [vueform/multiselect#277]
Good morning, 

I'm getting this error and noticing it only after scrolling through a long list then trying to search for an item after making several scroll attempts:

_ERROR:
runtime-core.esm-bundler.js:167 [Vue warn]: Unhandled error during execution of watcher callback 
  at <Multiselect class="multiselect-custom w-auto" modelValue=null onUpdate:modelValue=fn<onUpdate:modelValue>  ... > 
  at <App>
warn @ runtime-core.esm-bundler.js:167
multiselect.js:1765 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at observe (multiselect.js:1765:22)
    at flush (multiselect.js:1788:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js:284:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:293:21)
    at Array.job (runtime-core.esm-bundler.js:1891:17)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:484:47)
    at flushJobs (runtime-core.esm-bundler.js:529:9)_

Here is my element: 
`<Multiselect class="multiselect-custom w-auto" v-model="create.ScreenData.SelectedDutyStation" mode="single" placeholder="Select..." :close-on-select="true" :searchable="true" :infinite="true" :limit="10" :create-option="false" :clear-on-search="true" :min-chars="0" :options="shallowCore.CommonMenus.DutyStations"/>`
                               
If you just search for the result without scrolling it's not an issue. If you only scroll a couple times then search it's also often not an issue. Noticing this more with larger lists.

Thank you so much for taking the time out to look into this, really appreciate your time and assistance!

**Comment by thefunvampire** [comment]
I'm going to do some more testing, but it seems that adding attributes:

` :filter-results="true" :delay="0"`

As well as nesting the array variable in an async function like this:

```
:options="async function(query) {
        return shallowCore.CommonMenus.DutyStations;
        }"
```

may have resolved my issues. I will check back soon with more confirmation.

**Comment by thefunvampire** [comment]
I've narrowed it down further to just needing the Async wrap around my array and the :delay="0" attribute. Going to keep this open for a couple days so I can comment if necessary, but I think this is resolved.

**Comment by weddingdj** [comment]
Same issue here, and I had `async` in `:options` and `:delay="0"`. What solved id for me was to add `:close-on-select="true"`.
