### ISSUE TITLE
Right click trigger undesired actions

### ISSUE THREAD

**Issue by LeBenLeBen** [vueform/multiselect#28]
### Version

* Vue version: 3
* Plugin version: 1.2.5

### Description

Because the component listen to `mousedown` events, right clicks trigger actions just like a normal click.

For example if you right click on the button to delete an item — let’s say to inspect it — the item gets removed.

It would be better to listen to the click event to avoid this unexpected behavior.

**Comment by adamberecz** [comment]
Fixed in `1.3.1`.
