### ISSUE TITLE
[Bug] Search behavior on mode=tags

### ISSUE THREAD

**Issue by james-em** [vueform/multiselect#286]
Hi,

I would like to suggest a better behavior for the search functionality when in mode "tags" (multiple items).

**Current Behavior**

When you click the dropdown, options don't display because it focuses the hidden search text field. You must click the arrow.
When you start typing, results start to appear.

**Suggested Behavior**

When you click the dropdown, options display and you can start typing to filter the results.

Here is a non-vuejs library that implements this behavior https://tom-select.js.org/

Thank you!

**Comment by Mlekar** [comment]
Just to add, I think this broke with the latest release (2.5.7) due to the new wrapper container, works fine for me using 2.5.6 ver.

**Comment by james-em** [comment]
> Just to add, I think this broke with the latest release (2.5.7) due to the new wrapper container, works fine for me using 2.5.6 ver.

Are you suggesting that my feature request is actually a bug introduced in 2.5.7 ?

**Comment by pawel-omniaz** [comment]
@james-em It worked exactly how you described it in 2.5.6, now it's broken in 2.5.7.

**Comment by marcojanssen** [comment]
Any update on this? Ran into the exact same problem https://github.com/vueform/multiselect/issues/292 for the vuejs 3 version

**Comment by marcojanssen** [comment]
Can confirm that it works in 2.5.6 and is broken in 2.5.7

**Comment by adamberecz** [comment]
Fixed in `2.5.8`.
