### ISSUE TITLE
Keyboard focus is trapped on .multiselect-options element when search is enabled

### ISSUE THREAD

**Issue by LeBenLeBen** [vueform/multiselect#29]
### Version

* Vue version: 3

### Description

When you enable the `searchable` option:

1. Focus the multiselect field
2. Press "tab" to move the focus to the next focusable element
3. The `.multiselect-options` element catch the focus instead. This shouldn’t happen since this element is hidden.

### Demo

https://codesandbox.io/s/festive-glitter-ujwnh?file=/src/App.vue

**Comment by adamberecz** [comment]
Fixed in `1.3.1`. Actually it switched to an option because they are using `<a>` which is focusable. Now it should be fine.

**Comment by Maiquu** [comment]
This issue is still present in latest version of Firefox.

**Comment by adamberecz** [comment]
> While it works fine in Chrome, this issue is still present in latest version of Firefox.

True. I've looked into it and in fact it's a Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1069739

Could be solved with `tabindex="-1"` but that introduces other issues. Might be solved along with #35 , but not sure yet how.
