### ISSUE TITLE
@vueform/multiselect doesn't appear to be written in CJS

### ISSUE THREAD

**Issue by surya-soi** [vueform/multiselect#290]
@vueform/multiselect doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

**Comment by negezor** [comment]
Duplicate #258

**Comment by adamberecz** [comment]
From `2.6.0` the `module` now points to an `.mjs`. Hope this fixes - if not please reopen.
