### ISSUE TITLE
Issue about modal use

### ISSUE THREAD

**Issue by creativalab** [vueform/multiselect#295]
Hi, using "tags" mode in a modal form, when i try to delete a "tag" modal was closed. How can i add stop propagation?

**Comment by adamberecz** [comment]
Fixed in `2.5.8`.

**Comment by creativalab** [comment]
Hi, this seems work but not still, See my video thanks

https://user-images.githubusercontent.com/38782159/214554058-0795a11d-6ef1-4581-a00c-0fcdf2bf9c14.mp4
