### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by SunaPanaReloaded** [vueform/multiselect#3]
<img width="1276" alt="Screenshot 2020-12-23 at 1 29 21 PM" src="https://user-images.githubusercontent.com/75439854/102973633-1b5a3280-4523-11eb-8a18-84b32cc7dae7.png">

I've followed all steps exactly as instructed, still getting this error. When I installed Multiselect a couple of days back I didn't get such errors. Today installed a fresh copy for my project and it throws this error.

**Comment by adamberecz** [comment]
Please send the Multiselect options you are using. Are you using Vue 2 or 3?

**Comment by SunaPanaReloaded** [comment]
> Please send the Multiselect options you are using. Are you using Vue 2 or 3?

I am using Vue 3.

`<Multiselect v-model="mVal" :options="options" />`

I have done the import as necessary. Below are screenshots.

<img width="516" alt="Screenshot 2020-12-23 at 1 41 35 PM" src="https://user-images.githubusercontent.com/75439854/102974569-c5868a00-4524-11eb-86b6-c4b45767e5ec.png">
<img width="445" alt="Screenshot 2020-12-23 at 1 42 29 PM" src="https://user-images.githubusercontent.com/75439854/102974580-c7504d80-4524-11eb-9a64-1c23d5a19ec1.png">

In addition to this I am also getting a lot of warnings like below:

<img width="1271" alt="Screenshot 2020-12-23 at 1 43 56 PM" src="https://user-images.githubusercontent.com/75439854/102974727-08486200-4525-11eb-9b9d-64cda5737484.png">
<img width="1280" alt="Screenshot 2020-12-23 at 1 44 16 PM" src="https://user-images.githubusercontent.com/75439854/102974734-0aaabc00-4525-11eb-9341-78aa1c899415.png">

**Comment by adamberecz** [comment]
Strange, I'm not able to reproduce this, it's working fine with Vue 3 on my end. Try creating a new component containing only this:

``` vue
<template>
  <div>
    <Multiselect v-model="mVal" :options="options" />
  </div>
</template>

<script>
  import Multiselect from '@vueform/multiselect'
  import '@vueform/multiselect/themes/default.css'

  export default {
    components: {
      Multiselect,
    },
    data() {
      return {
        mVal: '',
        options: ['Batman', 'Robin', 'Joker']
      }
    },
  }
</script>
```

Does it still throws the errors?

**Comment by SunaPanaReloaded** [comment]
> Strange, I'm not able to reproduce this, it's working fine with Vue 3 on my end. Try creating a new component containing only this:
> 
> ```
> <template>
>   <div>
>     <Multiselect v-model="mVal" :options="options" />
>   </div>
> </template>
> 
> <script>
>   import Multiselect from '@vueform/multiselect'
>   import '@vueform/multiselect/themes/default.css'
> 
>   export default {
>     components: {
>       Multiselect,
>     },
>     data() {
>       return {
>         mVal: '',
>         options: ['Batman', 'Robin', 'Joker']
>       }
>     },
>   }
> </script>
> ```
> 
> Does it still throws the errors?

Yes, I tried creating a new component like suggested, but it still throws the same error. I am not sure how to find the error on my side, because when I remove Multiselect everything seems to be working fine.

**Comment by adamberecz** [comment]
Couple of ideas: 
- remove node_modules / package.json & npm install
- try importing `@vueform/multiselect/src/Multiselect.vue` instead of `@vueform/multiselect` - does still throws the error? If yes, send a screenshot as the error message should be more detailed.
- what exact Vue 3 version & @vueform/multiselect versions you are using? Are you within Vue CLI project?
- if nothing works you must create a repo which reproduces the bug so I can look into it.

**Comment by SunaPanaReloaded** [comment]
> Couple of ideas:
> 
> * remove node_modules / package-lock.json & npm install
> * try importing `@vueform/multiselect/src/Multiselect.vue` instead of `@vueform/multiselect` - does still throws the error? If yes, send a screenshot as the error message should be more detailed.
> * what exact Vue 3 version & @vueform/multiselect versions you are using? Are you within Vue CLI project?
> * if nothing works you must create a repo which reproduces the bug so I can look into it.

Absolutely no clue why, but when I removed node_modules and package-lock.json, then did npm install, worked!!! Thank you for your time, really appreciate it.

**Comment by adamberecz** [comment]
Glad it worked!
