### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by MartinKravec** [vueform/multiselect#30]
Hello, is it possible to add these features?
1) clear button to remove all values in v-model. It's not very user friendly to remove 200 tags manually
2) close prop, so that I can close options list when I pick value from multiple/tags mode
3) limit options list to given length

**Comment by c4y** [comment]
+1 for No. 2
You can help yourself with @select="closeOptionLists" Event and

methods: {
  closeOptionLists: function() {
     document.querySelectorAll('.multiselect-input').forEach(function (el) {
        el.blur();
      });
  }
}

**Comment by adamberecz** [comment]
Added all 2 in `1.3.1` @MartinKravec (the third should already exist).

1) Now it should automatically appear over the caret when `multiple` or `tags` mode has any selected options
2) Check out now [API docs](https://github.com/vueform/multiselect#api) section
3) Isn't `limit` in [props section](https://github.com/vueform/multiselect#basic-props) what you're looking for?

**Comment by luxterful** [comment]
I think also a interesting feature would be **loading more options on scrolling**.
I have a API that is using **paging** so would be dope if i could load more options of the other pages by scrolling the list till the end.

**Comment by c4y** [comment]
I think it would be great if you could group the options together

Group-Title 1
- Option 1
- Option 2
Group-Title 2
- Option 3
- Option 4

![group](https://user-images.githubusercontent.com/808164/107406165-6eef0280-6b08-11eb-889e-56ad851f0514.JPG)

**Comment by adamberecz** [comment]
Closing this because we have #24 for groups. Feel free to create a new one with scroll-loading.
