### ISSUE TITLE
Options list closes on select in tags mode even with closeOnSelect set

### ISSUE THREAD

**Issue by NeilMcEachin** [vueform/multiselect#300]
### Version

* Vue version: 3 

### Description

Seems to be a bug where options closes after selecting an option. If using `mode="tags"` and `:searchable="true"` even if `:close-on-select="false"` . Also seems related to another bug where option list does not open on search focus which is described in this ticket #286 

confirmed it is working correctly in 2.5.6

### Demo
You can see it not working example #5 in https://jsfiddle.net/t421d7cg/

**Comment by georginklv** [comment]
Still closing for me anyone to something about it ?
