### ISSUE TITLE
hideSelected="false" is not working in multiple mode

### ISSUE THREAD

**Issue by james-em** [vueform/multiselect#308]
### Version

Vue 3
VueForm 2.5.8

### Description

```
      <Multiselect
        placeholder="Régions"
        v-model="selectedRegions"
        mode="multiple"
        :hideSelected="false"
        :options="regions.map((r) => ({ label: r.name, value: r.id }))"
        @select="onRegionSelected"
      >
```

Selected items are hidden despite the fact it's being asked to not

### Demo

https://jsfiddle.net/2wgty9uh/

**Comment by adamberecz** [comment]
Try `:hide-selected` - native HTML transforms tags & attributes to lowercase.

https://jsfiddle.net/teqcox71/
