### ISSUE TITLE
Style precedence with tailwind

### ISSUE THREAD

**Issue by Fuzzyma** [vueform/multiselect#309]
### Version

* Vue version: 3

### Description

Using this component while using tailwind in my project as well leads to css precedence issues.
The base tailwind styles for inputs always overwrite the ones defined in the multi-select css.

It ends up looking like this:
![grafik](https://user-images.githubusercontent.com/3540542/212266225-369f9c44-7d83-418c-802c-94e3c084b37b.png)
![grafik](https://user-images.githubusercontent.com/3540542/212266277-40f1b114-27b3-4156-acbe-69c35d757e9c.png)

The styles are off. Here you can see, how the base classes overwrite the ones from this plugin
![grafik](https://user-images.githubusercontent.com/3540542/212266353-16733e86-0059-4ba1-b3d9-f1067521e790.png)

I also tried importing the styled differenly, use tailwind.css vs default.css, import the vue component directly, import the styles from style tag and so on. While this changed the style sometimes a little, it never fixed it.

### Demo

This setup is hard to reproduce since my own tailwind installation plays part in it.
However, it also might be that this is related to vite not sorting the styles correctly.

Did you ever see this issue and maybe have an idea on how to fix it?

**Comment by adamberecz** [comment]
As far as I know this was addressed in #134. If you import tailwind.css (and not default.css) **after** Tailwind CSS styles this should not be an issue.

Assuming by "base tailwind styles" you actually mean [tailwindcss-forms](https://github.com/tailwindlabs/tailwindcss-forms).

Feel free to reopen if you still experience the issue.

**Comment by Fuzzyma** [comment]
Your linked issue was resolved long time ago and I was on the newest version. So I dont think it was fixed there. However I moved on since I couldnt fix it so it doesnt matter to me

**Comment by adamberecz** [comment]
Got it. Just putting a note here that I was also on the newest version when testing it out and it did work on that. The earlier issue was the resolution of the original problem but it only gets applied if tailwind.css is imported after Tailwind CSS styles.
