### ISSUE TITLE
If selected dropdown value, unable to close dropdown event when selected value clicked or touched

### ISSUE THREAD

**Issue by racechand** [vueform/multiselect#310]
### Version

* Vue version: 3

### Description

If selected dropdown value, unable to close dropdown event when selected value clicked or touched.
We have mobile browser app. If selected dropdown value, unable to close dropdown event when selected value clicked or touched. If caret button very small, user able identify close or open. I decided use open and close event to manage validate and allow click selected value to close dropdown. This is not working as per expected.

Expected result: when click or touch selected value, that time close the dropdown.

Local Application Demo
[screen-recording.webm](https://user-images.githubusercontent.com/9251177/213181025-55ccdee1-9b4e-435b-88b9-efafa9b417dd.webm)

Kindly share your comments in this regards.

**Comment by adamberecz** [comment]
Added `closeOnDeselect` prop in `2.6.0`. You can simply set that to `true`.
