### ISSUE TITLE
Specific issue with prefilling tags

### ISSUE THREAD

**Issue by JoppeDC** [vueform/multiselect#312]
In one of our projects we're having an issue with prefilling tags. Not sure if this is directly Vueform related, but i've been breaking my head over it and  need some help..

Case:

We use the Multiselect component with async options as tags. 
When the page is loaded, the options as fetched from an API endpoint. When the user searches in the input, we also do an API call.

Options can also be prefilled, we do this using the `:model-value` prop. These prefilled options are also loaded via an API, and passed as props.

The problem:
Our API does not return all possible choices, as this is too many. It returns the first 100.
When loading the page, if the preset data is in the data that the api returns, it gets prefilled correctly.

Problem is, if you search in the multiselect field, and select an option that is not within the initial options, this no longer gets preset on pageload.

The options is available in `props.value`, but is not "added" to the multiselect.

<details>
  <summary>The code</summary>
  
Component
  ```js
<Multiselect
        v-model="selected"
        :options="choiceLoader"
        mode="tags"
        :searchable="true"
        :placeholder="trans('filters.placeholder.label')"
        :close-on-select="true"
        :filter-results="false"
        :resolve-on-load="true"
        :delay="0"
        :allow-empty="true"
        @change="updateFilterData"
        @open="updateOptions"
        ref="multiselect"
        :model-value = props.value
    />

<script setup>
.....
        const selected = ref([])

        function updateOptions() {
            multiselect.value.refreshOptions()
        }

        const choiceLoader = async function(query) {
          .........
    
          return await fetch(endpoint, {method: 'POST', body: JSON.stringify(body)})
            .then(response => response.json());
        }
</script>

  ```

As we can see here, we pass `props.value` as our preset data. When the component is initially loaded, this prop is an empty array. The data is then added when the fetch in the parent component finishes.
</details>

The solution?
The solution would be that these "prefilled" choices get added, whether or not they're in the available choices list.
You can do this using the `object` configuration, as shown in one of the demo's, but this does not appear to work with a reactive value (props.value).

Any ideas?

Massive thanks in advance!

**Comment by adamberecz** [comment]
The only option in this case (currently) is using `object`. I'm not sure what you mean with "not appear to work with a reactive value (props.value)" as it should. Could you please maybe create a demo presenting this issue? https://jsfiddle.net/5yxpmw4v/

**Comment by JoppeDC** [comment]
Hi @adamberecz ,

Sorry for the long wait. It's been quite busy, but i finally got the time to put together a small demo.

So the issue is as follows:
https://codesandbox.io/s/jolly-lake-nkfcv1?file=/src/App.vue
(For some reason no styling, but you can still see the issue)

The `model-value` prop that we can send to Multiselect does not appear to be reactive (It does not get updated automatically)

**Comment by adamberecz** [comment]
Things are working fine, you were just passing a function as a value to the Multiselect, which does not make sense.

Here's a fixed version for what you were trying to achieve:
https://codesandbox.io/s/value-not-preselected-forked-hqfux7?file=/src/components/autocomplete.vue

**Comment by JoppeDC** [comment]
Hi @adamberecz , Thanks for the feedback. It was indeed a combination of using the Object mode together with the Watch function that made it possible.
Obviously i was only able to show one example of what i tried in the sandbox, but i had tried at least 5-6 different methods. Including the Object mode, and the watch function, but not the combination of the two.

We've been able to resolve our issue now. Thanks a lot!
