### ISSUE TITLE
Label of the selected item is updated incorrectly when using `object` and options change

### ISSUE THREAD

**Issue by FichteFoll** [vueform/multiselect#315]
### Version

* Vue version: 2.7

### Description

This one took me quite a while to figure out. 

Basically, when using a single select with `object` mode, picking the selected item from the list of options (because they are compared by equality natively) and the options are updated, there is a watcher in `useOptions` that triggers `refreshLabels`, which ends up setting the label of the selected item to the first option unconditionally. The result is that the label does not represent the selected value anymore and that a property of the parent is mutated directly (i.e. without a corresponding `emit('input', …)`).

### Demo

```html
<script setup lang="ts">
import { computed, ref } from 'vue';

import Multiselect from '@vueform/multiselect/dist/multiselect.vue2.js';

interface Item { text: string; i: number}

class Option {
    constructor(
        public label: string,
        public value: Item,
        public disabled: boolean,
    ) {}

    static of(item: Item) {
        return new Option(
            `${item.text} - ${item.i}`,
            item,
            false,
        );
    }
}

const items = ref<Array<Item>>([]);

const options = computed(() => items.value.map(Option.of) ?? []);

const nativeValue = { text: 'test2', i: 2 };

const value = computed(() => options.value.find(opt => opt.value.i === nativeValue.i));

const multiselect = ref<InstanceType<typeof Multiselect> | null>(null)

setTimeout(() => {
  items.value = [
    { text: 'test', i: 0 },
    { text: 'test1', i: 1 },
    { text: 'test2', i: 2 },
  ];
}, 400);

</script>

<template>
  <div>
    <p>
      Multiselect update test
    </p>
    <Multiselect
      ref="multiselect"
      :value="value"
      :options="options"
      object
      searchable
    />
    <br>
    <input type="text" />
  </div>
</template>

<style src="@vueform/multiselect/themes/default.css"></style>
```

![2023-02-03_17-33-17](https://user-images.githubusercontent.com/931051/216657009-4d54f7b6-8ee6-47bb-801a-f370ef7c9340.png)

![2023-02-03_17-34-31](https://user-images.githubusercontent.com/931051/216657043-49cc1011-753c-4b5d-80ae-03eb75c7214f.png)

### Workarounds

My current workaround is to define a getter for `label` only.

I'd also be happy with another solution to select the current item based on a field of the object value, e.g. `Item.i`.

**Comment by FichteFoll** [comment]
Can also be reproduced slightly differently if the selected value is a normal `ref`:
```js
const value = ref({ label: 'tmp', value: nativeValue});
```
except now the value is not selected in the dropdown (since it's a different object).

![2023-02-03_17-43-05](https://user-images.githubusercontent.com/931051/216658778-9c9363a7-1b0d-4abc-b19d-235f93606f2f.png)

**Comment by adamberecz** [comment]
You should have:

```js
static of(item: Item) {
  return new Option(
    `${item.text} - ${item.i}`,
    item.i, // <-- note the `.i`
    false,
  );
}
```

You can also access an option based on value with:

```js
multiselect.value.getOption(2)
```

So the multiselect value can be set like this:

```js
const value = ref(value)

value.value = multiselect.value.getOption(2)
```

Hope this helps - feel free to reopen if you still have an issue or questions.

ps: I always appreciate a reproducible example using the link from our issue template (or anything else):
https://github.com/vueform/multiselect/issues/new?assignees=&labels=&template=1_bugs.md

**Comment by FichteFoll** [comment]
Thanks for taking a look. I won't have time to look at this over the next few days but will report back once I have.
