### ISSUE TITLE
Not strict equality of option values (1 or true)

### ISSUE THREAD

**Issue by tpuida** [vueform/multiselect#316]
### Version

* Vue version: 3

### Description
The multiselect got the following options:

``` 
[{
	"label": "Nil value",
	"value": null
}, {
	"label": "String value",
	"value": "a"
}, {
	"label": "Integer value",
	"value": 1
}, {
	"label": "Boolean value",
	"value": true
}] 
```

When a user selects "Integer value" or "Boolean value" two options shows like selected.
### Demo

Look at [JSFiddle](https://jsfiddle.net/timpuyda/oq8de1sc/3/) to reproduce the bug

**Comment by adamberecz** [comment]
Thanks for the report. Fixed in `2.6.0`.
