### ISSUE TITLE
How to disable a selected tag and prevent it from getting deleted?

### ISSUE THREAD

**Issue by benmwendwa** [vueform/multiselect#318]
When using  `mode='tags'`, a selected tag can be deleted by using the backspace/delete key or by clicking the `x`  or close icon.
Using a custom tags slot, its possible to hide the `x` icon, but the tag will still be deleted using backspace key.
How can this be prevented?

I created a JSFiddle example showing above cases.
https://jsfiddle.net/uvnw0khx/

**Comment by adamberecz** [comment]
From `2.6.0` you can add either `remove: false` to the option or `disabled: true`. If you add `disabled: true` you might don't even need a custom template but it will have disabled style (which you can override with custom CSS if that's easier).
