### ISSUE TITLE
Styling with tailwind css configuration

### ISSUE THREAD

**Issue by paulinad98** [vueform/multiselect#322]
Hello,
It is necessary to add information about installing the package https://www.npmjs.com/package/mini-svg-data-uri. In addition, tailwind's styles importing address ('path/to/node_modules/@vueform/multiselect/themes/tailwind.css') does not work. It must be replaced with an address '@vueform/multiselect/themes/tailwind.css'.  :)

**Comment by adamberecz** [comment]
Thanks
