### ISSUE TITLE
Stop propagation does still not work

### ISSUE THREAD

**Issue by creativalab** [vueform/multiselect#323]
Hi, as i posted in issue #295, it seems there is an issue about last tag. 
When i click on last tag modal has  been closed.
See my video thanks.

https://user-images.githubusercontent.com/38782159/226682459-7a10132e-d2a9-420c-8a17-6c8d72fd5540.mp4

**Comment by adamberecz** [comment]
I can't reproduce this based on a screencast. Feel free to reopen with a reproducible example link.
