### ISSUE TITLE
Hide "The list is empty"

### ISSUE THREAD

**Issue by permagne** [vueform/multiselect#327]
While creating an async autocomplete, I need to be able to hide "The list is empty" until the user has actually searched for something and gotten back an empty result. None of the async examples seem to handle this. 
Any ideas?
Thanks

**Comment by darkons** [comment]
The **noOptionsText** (default: The list is empty) is only for empty selects, that is with no options.
The **noResultsText** (default: No results found) is only displayed when you perform a search but no option matches the query (don't work with async options).

In you case, you can add:
```js
no-options-text="Type to search an user"
no-results-text="The user was not found"
```
