### ISSUE TITLE
setting v-model to an undefined object property then setting the property at runtime doesnt work

### ISSUE THREAD

**Issue by XiDanko** [vueform/multiselect#328]
### Version

* Vue version: 3
* Multiselect version: after 2.4.2 till 2.6.1

### Description

when setting multiselect v-model to an empty object property (that will be provided at run time) multiselect wont select the option even after providing the property with valid value at run time
ps: it was working on version 2.4.2 and below
ps: this behavior also exists in toggle package it was working on version 2.0.2 and below

### Demo
https://jsfiddle.net/vg6xs29m/1/

**Comment by kberawala** [comment]
one up for the issue ? any suggestions / solutions ?

**Comment by yogesh-gohil** [comment]
can you check this ? and let me know if any confusion.

https://jsfiddle.net/ubLo1pvj/

**Comment by XiDanko** [comment]
@yogesh-gohil there is not confusion i dont want to bind to an object i want to bind to an object property

**Comment by klausbetz** [comment]
@XiDanko Lately, I ran in the described issue using `2.5.6`. Unfortunately, updating to `2.6.2` didn't improve the behavior.

When the passed-in v-model is `undefined` at first, it won't be reconsidered when updating it later on asynchronously.

This [PR](https://github.com/vueform/multiselect/pull/356) should fix this issue by keeping the reference to the original v-model alive using an internal computed property.

**Comment by XiDanko** [comment]
@klausbetz thank you for sharing your fix
i hope they merge it in the next release
i found the same problem with their toggle library as well
