### ISSUE TITLE
Ho can a use tags mode without open a select?

### ISSUE THREAD

**Issue by andersonalvesalmeida** [vueform/multiselect#33]
Is there any way to use the tags mode without opening the select?

I just want to add new strings without the option to select any string from the list.

Tanks

**Comment by marcreichel** [comment]
In addition I would like to just provide the `v-model` without the `:options` to populate the initial loaded tags.

Would be really nice if those two features could be added in future releases.

**Comment by marcreichel** [comment]
@andersonalvesalmeida As a workaround you can hide the `.multiselect-options` via CSS:

```css
.multiselect > .multiselect-options {
    display: none;
}
```

**Comment by adamberecz** [comment]
Added `showOptions` prop in `1.3.3`
