### ISSUE TITLE
Backspace on mode=tags does not fire the deselect event

### ISSUE THREAD

**Issue by evankford** [vueform/multiselect#335]
### Version

* Vue version: 3

### Description

When using `mode="tags"` and `searchable`, backspace successfully removes the tag, but it does not fire the `deselect` event.

### Demo
https://jsfiddle.net/05mokgqt/9/

**Comment by Adeiko** [comment]
Did anyone find any workaround for this? 
I'm currently having to use a different object with the current selections and making a diff on each change to keep them in sync
