### ISSUE TITLE
html5 validation - missing required

### ISSUE THREAD

**Issue by batuotasis** [vueform/multiselect#34]
We use html5 validation in our project and consider using the library, but we miss one feature the "required" attribute. Is there any way to get it?

**Comment by N05h3ll** [comment]
Got the same issue here, the component is missing a required attribute.
I think a temporarily workaround is to validate the " :v-model = 'value' " attribute if the length = 0.

**Comment by web4social** [comment]
We also need the "required" attribute

**Comment by adamberecz** [comment]
It wasn't trivial because multiselect is in fact a just a `div`, not an actual HTML `input`, but managed to do it with a fake input. Please update to `1.3.3` and set `required` to `true`.

**Comment by gerbenvandijk** [comment]
Yup I got that from the comments here @adamberecz - but it is not in the documentation right? i was searching for quite a while in the documentation on the [vueform site](https://vueform.com/reference/1.x/multiselect-element) and did not find it, I found this ticket via a Google search. I think it would be great if this feature could be documented 👍
