### ISSUE TITLE
Append dropdown to body

### ISSUE THREAD

**Issue by mrleblanc101** [vueform/multiselect#341]
### Version

* Vue version: 2 and 3

### Description

Currently, the dropdown is a child of the component, it should be appended to the body using a `<Teleport>` (Vue 3) / `<Portal>` (Vue 2) to prevent making an `overflow-y: auto;` scrollable (ex: Inside a modal).

### Demo
![2023-05-17 16 04 52](https://github.com/vueform/multiselect/assets/17392251/5765867a-e9a2-4078-8d7f-3418cb4355db)

Desired behavior (the dropdown should overlay everything):
![Capture d’écran, le 2023-05-17 à 16 05 30](https://github.com/vueform/multiselect/assets/17392251/03f79018-11d1-4313-bd88-337edb7e0422)

**Comment by farisnceit** [comment]
i'm also facing this issue need a solution

**Comment by vishnusree66** [comment]
any solution?

**Comment by hamonCordova** [comment]
Same problem here

**Comment by hellojessicagraham** [comment]
please? 🥺

**Comment by phanuwit007** [comment]
please !!

**Comment by MohamedHana** [comment]
> ### Version
> * Vue version: 2 and 3
> 
> ### Description
> Currently, the dropdown is a child of the component, it should be appended to the body using a (Vue 3) / (Vue 2) to prevent making an `overflow-y: auto;` scrollable (ex: Inside a modal).
> 
> ### Demo
> ![2023-05-17 16 04 52](https://user-images.githubusercontent.com/17392251/239066169-5765867a-e9a2-4078-8d7f-3418cb4355db.gif)
> 
> Desired behavior (the dropdown should overlay everything): ![Capture d’écran, le 2023-05-17 à 16 05 30](https://user-images.githubusercontent.com/17392251/239066190-03f79018-11d1-4313-bd88-337edb7e0422.png)

To have the desired behavior the modal body should not be scrollable.

**Comment by MohamedHana** [comment]
To have the desired behavior the modal body should not be scrollable.

**Comment by mrleblanc101** [comment]
> To have the desired behavior the modal body should not be scrollable.

@MohamedHana You're missing the point, I want the modal body to be scrollable if it has long content, I don't want the dropdown to trigger the scroll. The dropdown should be appended to the body of the page like every dropdown library does (like Popper.js)

**Comment by adamberecz** [comment]
Thank you for the patience guys. It's now implemented in `2.6.3` and can be enabled with `appendToBody: true`. It's still experiemental and only works in Vue.js 3 so please open an issue if you encounter any problems.
