### ISSUE TITLE
Long tags do not get truncated

### ISSUE THREAD

**Issue by sh-ravan** [vueform/multiselect#346]
### Version

* Vue version: 3

### Description

Currently, there's no way to truncate long tags. Can we please have a property that can define if tags are truncated after a user-specified/default length?

![image](https://github.com/vueform/multiselect/assets/83463078/37ffbfa6-9223-4f90-8556-bec77b676b8c)

![image](https://github.com/vueform/multiselect/assets/83463078/0713cb53-34c7-4a7f-945a-b349ccd64f69)

**Comment by shriDeveloper** [comment]
Hi did you solve this issue ?

**Comment by Adeiko** [comment]
> Hi did you solve this issue ?

Not really a soluction but you can enable the wrap in the multiselect-tag as a workaround.

```
.multiselect-tag {
  white-space: wrap;
}
```

**Comment by adamberecz** [comment]
Fixed in `2.6.3`. Longs tags are now automatically truncated. You can use `breakTags` prop to optionally break long tags into multiple lines.
