### ISSUE TITLE
Unable to scroll multiselect component dropdown within modal

### ISSUE THREAD

**Issue by romharada** [vueform/multiselect#35]
### Version

* Vue version:  3

### Description

Unable to scroll through dropdown options whenever multiselect component is inside div element with tabindex value assigned.

I need to use such component inside a modal whose tabindex value is set to "-1" by default. When I try scrolling through dropdown options by clicking anywhere in the scrollbar, the dropdown list is immediately closes, losing focus. Any parent div element with any tabindex value  assigned (not empty) causes this behavior. It's important to note that scrolling works by using the keyboard or mouse wheel. I'm able to select items in this dropdown list by clicking them, it's only a scrollbar issue.

### Demo
https://jsfiddle.net/x5yhzou2/1/

**Comment by adamberecz** [comment]
I haven't been able to fix this in the latest patch. Does anyone have any idea how to solve this?

**Comment by adamberecz** [comment]
It's solved in `2.0.0`.
