### ISSUE TITLE
Dropdown won't generate using axios

### ISSUE THREAD

**Issue by justmealf** [vueform/multiselect#350]
Hi, i want to generate dropdown from axios but it wont generate it was same as #6 example returning value and label, but it wont generate

`
axios.get()
........
.then((response) => {
      console.log(response);
      console.log(response.data);
      return response.data.map((item) => {
            return { value: item.name, label: item.label};
        })
    })
    .catch((error) => {
      console.log(error)
    });
`

**Comment by adamberecz** [comment]
Please create a reproduction then reopen.
