### ISSUE TITLE
Error when calling refreshOptions

### ISSUE THREAD

**Issue by Kocarik** [vueform/multiselect#351]
Vue version: 3

Error (see image) when calling multiselectRef.value.**refreshOptions()**
![image](https://github.com/vueform/multiselect/assets/15687687/b9a1f644-1ee8-448f-b54a-ec56614db980)
![image](https://github.com/vueform/multiselect/assets/15687687/149d7419-7a4f-4280-9869-b767ec0f557a)

**Comment by adamberecz** [comment]
Please create a reproduction then reopen.
