### ISSUE TITLE
[Feature request] Ability to hide the dropdown

### ISSUE THREAD

**Issue by tpuida** [vueform/multiselect#361]
In my case, `create-option` is set as `true`, in `tags` mode. User should create their own tags only. So `options` should be []. Neither empty `noOptionsText` nor by slot I cannot hide the dropdown.

**Comment by almerleoalmazan** [comment]
Experiencing the same issue.

**Comment by adamberecz** [comment]
Isn't `showOptions` prop is what you're looking for?

**Comment by tpuida** [comment]
> Isn't `showOptions` prop is what you're looking for?

Yes, it works. Thank you
