### ISSUE TITLE
Caret slot is not working

### ISSUE THREAD

**Issue by abdul-alhasany** [vueform/multiselect#368]
### Version

* Vue version: 3

### Description

When attempting to replace the caret using the slot component, nothing happens. The original caret stays the same and is not replaced.

### Demo

https://stackblitz.com/edit/vitejs-vite-7ujuuh?file=tailwind.config.js,src%2FApp.vue

**Comment by Zeeex** [comment]
![image](https://github.com/vueform/multiselect/assets/16362320/0e0a9845-a7f7-49e0-bc34-97edfe47bc15)

It should be #caret, and not #cart

**Comment by abdul-alhasany** [comment]
Thanks for that. I can't believe that I spent such a long time because of a typo.
