### ISSUE TITLE
Append dropdown to body positioning off when scrolling

### ISSUE THREAD

**Issue by victorlap** [vueform/multiselect#370]
### Version

* Vue version: 3.2.47

### Description

When scrolling the body of the page. The dropdown seems to stay fixed to the page instead of scrolling together with the select component. See video https://github.com/vueform/multiselect/assets/1645632/b13e03b1-7345-4d3d-8915-112093e0aec3

### Demo

https://jsfiddle.net/qyfatevc/3/

**Comment by LanFeusT23** [comment]
I think that's why they added `closeOnScroll` if you scroll it's not really likely for you to need the dropdown to stay open.

**Comment by victorlap** [comment]
It's not only that, the problem is the same if you scroll before opening the dropdown, then the dropdown is positioned incorrectly (or off the page completely if you scroll more than 100vh)

**Comment by Zeeex** [comment]
Probably chosen for the size, but isn't [Floating UI](https://floating-ui.com/) a better option, because it is the successor of PopperJS?
