### ISSUE TITLE
Small regression / bug in 2.6.6 for id generation

### ISSUE THREAD

**Issue by Zeeex** [vueform/multiselect#373]
### Version

* Vue version: Latest 3.x

### Description

The changes you've added in 2.6.6 for "Added ${id}-dropdown to dropdown DOM" made it so if the id isn't specified, it adds undefined.

![image](https://github.com/vueform/multiselect/assets/16362320/cc7b9c4e-259b-4e56-b84e-6ed5a943a3a6)

My suggestion would be to generate a unique ID if you need to have it at all times (better option, like id="skdngrk3ls9-dropdown"), or / and to have a check if the id is passed before creating a new id.

**Comment by reslear** [comment]
hi @adamberecz do we even need an `id` here ?)

https://github.com/vueform/multiselect/blob/main/src/Multiselect.vue#L173

Suggestion:
- remove if not specified
- use some https://github.com/ai/nanoid for default generation.
