### ISSUE TITLE
.select() after .refreshOptions() race

### ISSUE THREAD

**Issue by dangerdan** [vueform/multiselect#38]
### Version

* Vue version: 3

### Description

I'm using a callback in refreshOptions to update the options for a rendered multi-select. Providing an option via this update that matches the value in modelValue isn't selected automatically, and I cannot select it via the .select() api as there is no promise or similar to respond to.

Is there a work-around or something I'm missing?

### Demo

```
this.$refs.input.refreshOptions(
          this.getItems().then(() => {
            this.$refs.input.select(this.modelValue); // this fails because the multi-select isn't yet up to date with the new options, I probably shouldn't have to do this at all considering the modelValue is already set.
          })
        );
```

**Comment by adamberecz** [comment]
Could you provide a full, working example? This even has syntax error.

**Comment by adamberecz** [comment]
Closed due to inactivity. Feel free to reopen.
