### ISSUE TITLE
Click on scrollbar closes multiselect when appendToBody or appendTo= is being used

### ISSUE THREAD

**Issue by UteV** [vueform/multiselect#383]
Version 2.2.6
Vue version: 3.3.9

When appendToBody or appendTo="" is used, scrolling with the scrollbar is impossible because clicking the scrollbar closes the dropdown.

See: [https://jsfiddle.net/hnzoq0sf/](url)

Tested on Chrome and Firefox

**Comment by sean-ccm** [comment]
+1

**Comment by JohnnyKraemer** [comment]
+1

**Comment by Olakeen** [comment]
+1
