### ISSUE TITLE
No types on scoped slotes

### ISSUE THREAD

**Issue by AlexKharenko** [vueform/multiselect#391]
Props from scoped slots always return never but it should have type for each prop. There is no difference if i use it like this

```
<template
        v-for="(_, slot) in $slots as unknown as Multiselect['$slots']"
        #[slot]="scope"
 >
        <slot :name="slot" v-bind="scope as object" />
</template> 
```

or like this

```
<template #option="{ option, isPointed, isSelected, search }">
        <div>{{ option.name }}</div>
</template>
```

All this props are never type and typescript is alerting that there is a problem.

Please, provide typescript support!

**Comment by adamberecz** [comment]
Thanks for reporting the issue. Fixed in `2.6.7`.
