### ISSUE TITLE
Cannot read properties of null (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by joffreyBerrier** [vueform/multiselect#394]
### Version

Nuxt@^3.10.0

### Description

I'm using Multiselect in a Nuxt application and I have this error a lot
`Cannot read properties of null (reading 'querySelectorAll')`
<img width="730" alt="Capture d’écran 2024-02-19 à 15 16 59" src="https://github.com/vueform/multiselect/assets/26119557/ec39256a-6cb0-4792-a8e4-7ac28204d16b">

### Demo

I don't have a demo but I have create a pull request to fix that

**Comment by joffreyBerrier** [comment]
The pull request https://github.com/vueform/multiselect/pull/395

**Comment by adamberecz** [comment]
Thanks for the PR. Released in `2.6.7`.
