### ISSUE TITLE
Option has not been selected when options are changed in runtime

### ISSUE THREAD

**Issue by MarekGogol** [vueform/multiselect#40]
### Version

* Vue version: ^3.0.5

### Description

1. Set value of options (you have value for example from query ?option_id=1)
2. then "fetch" options and add them after component is ready.
3. bug: selected option is not updated when options has been changed.

### Demo
https://jsfiddle.net/wxgf3vch/

**Comment by adamberecz** [comment]
Fixed in `1.3.4`.
