### ISSUE TITLE
Prefilled tags without providing options

### ISSUE THREAD

**Issue by marcreichel** [vueform/multiselect#41]
As mentioned in #33 I would like to be able to prefill tags by only using the `v-model`. Currently (v1.3.3) I need to provide `:options` with matching tags to prefill the tags input even when setting the new `showOptions`/`show-options` property to `false`.
That's redundant imo.

**Comment by adamberecz** [comment]
You can do that by using `object` values, otherwise Multiselect wouldn't know the label of an item.
