### ISSUE TITLE
appendToBody on async options: dropdown position is incorrect for the first time appearance

### ISSUE THREAD

**Issue by faizaaulia** [vueform/multiselect#413]
### Version

* Vue version: 3

### Description

Using appendToBody on async options select, the dropdown open position is incorrect for the first time. Then when the user scroll, the dropdown position will recalculate to the proper position

### Demo

I try it on your JSFiddle reproduction template is ok, [Reproduction from your template](https://jsfiddle.net/gvq641ck/3/)
But if I try it from your JSFiddle demo with addition on appendToBody, the dropdown position is not oke [Modified JSFiddle demo](https://jsfiddle.net/oyb4Lzts/4/)
I don't know what is the difference, but I set the same props on the both JSFiddle. So I can't really tell if it is an issue on the multiselect or just the layout. But here is my recording video: [Recording on bug](https://drive.google.com/file/d/1w826yxPv4vSiJ37EvGnq5ss4djaGCdTF/view?usp=sharing)

**Comment by adamberecz** [comment]
Resolved: https://discord.com/channels/787237947635793940/1250692495227228160/1251113911181119518

**Comment by Mukti123Raj** [comment]
Can anyone give the solution to this issue, as I am getting the same issue.

**Comment by faizaaulia** [comment]
> Can anyone give the solution to this issue, as I am getting the same issue.

the workaround is on https://jsfiddle.net/znhy0wuL/7/, it's the `.updatePopper()` after the fetch
