### ISSUE TITLE
Search containing spaces in single mode

### ISSUE THREAD

**Issue by rrpatricio** [vueform/multiselect#42]
Hi,

I'm having some trouble when the component is searcheable and the search term contains spaces. When the user types space, the first option of the combo is selected / deselected, making it impossible to search for more than one term. This can be seen in demo number 5 - _Autocomplete with async options_ (https://jsfiddle.net/q6Lnpr7a/). I'm not sure, but I suspect the problem is onKeyup event.

![image](https://user-images.githubusercontent.com/78457585/111831807-a3f03100-88ce-11eb-8c34-92c7d75e069c.png)

Could you check it, please?

Thank you very much.

**Comment by vesper8** [comment]
omg so glad to see i'm not alone losing my mind! this must be a new bug or a hell of a coincidence because i am all of a sudden having the exact same problem. @select fires on spaces

**Comment by vesper8** [comment]
This is the full error

**Comment by vesper8** [comment]
@rrpatricio @adamberecz can also confirm that setting it to version 1.3.2 (removing the ^) makes the problem going away. So it's something new in 1.3.4

**Comment by adamberecz** [comment]
Should be fixed in `1.3.5`. I've added quite a few tests and I hope all cases are covered. If you still have any issues with this please provide an example config.
