### ISSUE TITLE
Add event on `nooptions` or `noresults` click

### ISSUE THREAD

**Issue by vincenzoraco** [vueform/multiselect#43]
Hi there folks,

If the title is not already clear I try to explain what I mean and what I am trying to achieve. I am using Vue3 by the way.

I would like to have an event when the user clicks on the `nooptions` and `noresults` slots - just like the `@select` event. At the moment it doesn't work if I add a `@click` on the custom template slot as per below example:

```vue
<multiselect ...>
    <template v-slot:noresults>
        <div class="multiselect-option" @click="openModal">
            Create New
        </div>
    </template>
</multiselect>
```

Am I missing something or at the current stage it should not work until a custom event within the package is added?

**Comment by adamberecz** [comment]
Try using `@mousedown.prevent` instead of `@click`.
