### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jnarowski** [vueform/multiselect#44]
### Version

* Vue version: 2

### Description

I'm using Nuxt with the composition API and trying to get this plugin to work. When I try to load it, I get the above error:
Cannot use import statement outside a module

### Demo

Please use our [JSFiddle template](https://jsfiddle.net/29oyhqL5/) to reproduce the bug. Issues without working reproduction might be ignored.

[Here's a gist of the file.](https://gist.github.com/jnarowski/9e9bdf713ed8e7a5e682b114f805367c) Not doing anything special.

**Comment by jnarowski** [comment]
This is nuxtJS specific. If you want to add a NuxtJS example, here's how I fixed it:

**in nuxt.config.js**
`{ src: '~/plugins/vue-stack-grid', mode: 'client' }`

**in plugins/multiselect.js**
```
import Vue from 'vue'
import Multiselect from '@vueform/multiselect/dist/multiselect.vue2.js'
Vue.component('VMultiselect', Multiselect)
```

**In the component**
```
  <client-only>
    <v-multiselect v-model="value" :options="options" />
  </client-only>
```

**Comment by jnarowski** [comment]
This didn't end up working in Nuxt. I was getting errors about infinite loops so I had to try and find another plugin. I love what you did though with composition, it's so clean. Any interest in ensuring this works with Nuxt and Vue2?

**Comment by adamberecz** [comment]
I've created a section with Nuxt.js usage:
https://github.com/vueform/multiselect#using-with-nuxtjs

It works on a fresh install with this setup. If it's still not ok on your end please share your `nuxt.config.js`.

**Comment by adamberecz** [comment]
Feel free to reopen if you still have issue with this.

**Comment by jnarowski** [comment]
It's still not working and this seems like the cleanest select plugin out there by far! 

Here's my config:
https://gist.github.com/jnarowski/a740922bba3d9d1127ae239530773eaa

**Comment by jnarowski** [comment]
I recreated with a fresh nuxt install. 

Here's the code for it:
https://drive.google.com/file/d/12_r3SknguGWhaqvb2zwFTobo44wwcq5l/view?usp=sharing

Codesandbox was having issues getting the right Nuxt up and running. I'd love to use this if we can figure out what's going on. Maybe in the rollup settings?

**Comment by jnarowski** [comment]
Can we re-open this or should I create a new issue since it's still there?.

**Comment by PixsaOJ** [comment]
Can we get this fixed?

**Comment by IsraelOrtuno** [comment]
I think this should be opened again, bug is still there, no way to make it work with nuxt

**Comment by IsraelOrtuno** [comment]
I made it work by adding this to the nuxt config:

```
  build: {
    transpile: [
      '@vueform/multiselect/dist/multiselect.vue2.js',
    ],
  },
```

**Comment by PixsaOJ** [comment]
I used [Nuxt multiselect](https://www.npmjs.com/package/nuxt-multiselect)

**Comment by Grawl** [comment]
The same for Quasar Framework. To fix this error, I have to add `@vue-form/multiselect` to `build/transpileDependencies` in `quasar.conf.js`:

```js
module.exports = configure(function (ctx) {
	return {
		// …
		build: {
			// …
			transpileDependencies: [
				'@vueform/multiselect'
			],
			// …
		},
	// …
}
```

(Quasar v2 in my case)

**Comment by sthuber90** [comment]
With vue-cli the recommendation seems to be to adjust the [`transformIgnorePatterns`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-jest/README.md#transform-dependencies-from-node_modules) in your _jest.config.js_ file.

```js
module.exports = {
	// ...
	transformIgnorePatterns: ["/node_modules/(?!@vueform/multiselect)"],
}
```

This way testing the multiselect with [testing-library/vue](https://github.com/testing-library/vue-testing-library) works.
