### ISSUE TITLE
Problem when searching in component "tags with async options"

### ISSUE THREAD

**Issue by rrpatricio** [vueform/multiselect#45]
### Version

* Vue version: 3

### Description

Hi,

I'm having some trouble when doing some search in the "tags with async options". When the user do some search, pick an option and do another search that does not contain the first picked option, the component stop working. I'm not sure, but I suspect the problem is that the component try to retrieve some information about the tag in the options list but the option array doesn't have it on the second search.

### Demo

This issue can be easily reproduced in example number 6 - _Tags with async options_ (https://jsfiddle.net/q6Lnpr7a/).

     To reproduce this error:

     1 - Search for 'a';
     2 - Choose '@Formula' option;
     3 - Search for 'b';

![image](https://user-images.githubusercontent.com/78457585/112176691-13b83180-8bd7-11eb-9fa0-731cf5b916d5.png)

Thank you very much.

**Comment by adamberecz** [comment]
Should be fixed in `1.3.6`.

**Comment by danielhgasparin** [comment]
This issue has returned in version 1.4.0.
