### ISSUE TITLE
Tag ends with space symbol when add via "space"

### ISSUE THREAD

**Issue by narsiliko** [vueform/multiselect#46]
Added `addTagOn` [prop](https://github.com/vueform/multiselect#advanced-props) in `1.3.3`.

_Originally posted by @adamberecz in https://github.com/vueform/multiselect/issues/37#issuecomment-797565416_

When i'am adding new tags by space, every tag ends with space symbol.
```
tags:Array[3]
0:"123 "
1:"1235dcdcd "
2:"1232132 "
```

**Comment by adamberecz** [comment]
Fixed in `1.3.6`.
