### ISSUE TITLE
Show previously added options recieved from server when using async options search

### ISSUE THREAD

**Issue by narsiliko** [vueform/multiselect#47]
Show previously added options when using async options search

I`m using the select for async search options
```
      v-model="cities"
      mode="tags"
      :searchable="true"
      :options="async (query) => {
        return await fetchCities(query)
      }"
      :minChars="1"
      :resolveOnLoad="true"
      :delay="0"
```

I set resolveOnLoad="true", but how can I show tags, that asynchronously comes to v-model on form init, in the select field? Is there any way to set something like 'defaultOptions / initialOptions' when I`m "searching" for options and adding them as tags?

**Comment by adamberecz** [comment]
You can do that with `object` prop. The values will have to be objects in this case, but otherwise Multiselect wouldn't know all the information about an item (label + value).
