### ISSUE TITLE
Add input support for submitting forms in regular way

### ISSUE THREAD

**Issue by KirePetrov** [vueform/multiselect#48]
Hi guys,

I using Laravel and Vue and in some cases i have regular point to point form submission without ajax request.

When i place request to my controller, i can't see selected options in tag mode.

I found some work-around with @ change event to populate some hidden input, but it will be better if vue-multiselect package can handle this case.

my final work-around;
add this somewhere in vue component
`<input v-for="id in v-model" type="hidden" name="variable_name[]" :value="id" />`

Thanks.

**Comment by vipera** [comment]
I'm working on a hybrid app that isn't a full Vue SPA. I'd also benefit from this, as it would let me embed components as their own Vue apps in the page where they aren't a part of a richer component tree.

**Comment by adamberecz** [comment]
Added this in `1.5.0`. Use `nativeSupport: true` and you should have it.

**Comment by SimonHawesome** [comment]
If you need to customize the name attribute in the generated hidden inputs, you need to set the `name` prop in the `Multiselect` custom element.

```
<Multiselect :name"'customInputName'" />
```

Which will be rendered as 

```
<input type="hidden" name="customInputName[]">
```
