### ISSUE TITLE
Text being converted is overlapping when made apply searchable option.

### ISSUE THREAD

**Issue by sunecosuri** [vueform/multiselect#49]
# Reproduction environment
https://jsfiddle.net/sunecosuri/3otvkf1p/9/

If you try to enter the initial value while it is being entered and before it is converted, the text will overlap.
Is there any way to fix this?

https://user-images.githubusercontent.com/13265134/112277768-6cfe8e80-8cc5-11eb-987e-18a32c55e07c.mov

**Comment by vesper8** [comment]
I'm seeing this happen also but on mobile only. It doesn't happen when using a mobile simulator such as with using the Chrome Debugger, but on my actual mobile phone the text overlaps the placeholder, and in my case the search outright doesn't work either.. works perfectly on desktop though so am really confused

**Comment by adamberecz** [comment]
Probably related to #50

**Comment by adamberecz** [comment]
Should be fine from `1.3.6`.

**Comment by sunecosuri** [comment]
I confirmed that it was fixed successfully. Thank you very much!
