### ISSUE TITLE
does not work at all on Android

### ISSUE THREAD

**Issue by vesper8** [vueform/multiselect#50]
### Version 1.3.5

* Vue version: 2

### Description

This is a pretty big deal.. I just noticed this multiselect is completely unresponsive on my Android phone. It's not only my personal project, your own demo shows the same results https://jsfiddle.net/q6Lnpr7a/

Try the Autocomplete demo #5. I haven't tested it on IOS but on Android if you try to type inside the autocomplete box, the text goes on top of the placeholder, and it doesn't actually perform any search! It appears to perform a search when you tap outside the box, but then I think that also causes your text to disappear to it doesn't actually search.

Works perfectly on desktop. Also you can't reproduce this using Desktop Chrome's "device toolbar". Maybe you can reproduce it with GenyMotion/Xcode simulator.. hopefully you have an Android phone available.

**Comment by adamberecz** [comment]
Could you try this with [c11e5f9](https://github.com/vueform/multiselect/commit/c11e5f9527dd0e96ecf7f0c00d4465daeec65e7b)? Looks like Android doesn't trigger `input` event, so I've replaced it with `keyup`. Btw here's a free online emulator: https://www.apkonline.net/

**Comment by adamberecz** [comment]
Can you try this with [1b1d09a](https://github.com/vueform/multiselect/commit/1b1d09a15d36c30ca1459e8effd3f1221d433a5e)? I've replaced v-model with custom `:value/@input` as suggested here https://github.com/vuejs/vue/issues/9777#issuecomment-478831263 where it is also explained why you had this behaviour.

**Comment by vesper8** [comment]
I'm not sure how to test this. Can you make your jsfiddle demo use this new version so I can test it that way?

I had to scramble yesterday and replace the mobile version of the autocomplete using another library because I wasn't sure how long it would take for a fix and I couldn't have a broken search in production (my bad for not testing it more thoroughly)

**Comment by adamberecz** [comment]
Alright, I've released `1.3.6`, it should refresh in fiddle too soon.

**Comment by adamberecz** [comment]
Feel free to reopen if the issue persists after package update.
