### ISSUE TITLE
Bug cross and arrow

### ISSUE THREAD

**Issue by AdrigomRoc** [vueform/multiselect#53]
### Version

* Vue version: 
Vue 3
### Description

The cross and arrow when you select a person is a bit confusing to use. 
I was retouching it, and I have seen that it is due to the heigth default of the images, but I think that the optimal solution instead of hiding it due to overflow, hide it with a v-if if it detects that there is a selected value the arrow that disappears and becomes the cross and the other way around. regards!
### Demo

Please use our [JSFiddle template](https://jsfiddle.net/29oyhqL5/) to reproduce the bug. Issues without working reproduction might be ignored.
https://jsfiddle.net/2rnhytpg/
I don't know how that website works, but I think it's already here
----
 <Multiselect
    v-model="value"
    mode="tags"
    placeholder="Select employees"
    trackBy="name"
    label="name"
    :search="true"
    :options="[
      {
        value: 'judy',
        name: 'Judy',
        image: 'https://randomuser.me/api/portraits/med/women/1.jpg',
      },
      {
        value: 'jane',
        name: 'Jane',
        image: 'https://randomuser.me/api/portraits/med/women/2.jpg',
      },
      {
        value: 'john',
        name: 'John',
        image: 'https://randomuser.me/api/portraits/med/men/1.jpg',
      },
      {
        value: 'joe',
        name: 'Joe',
        image: 'https://randomuser.me/api/portraits/med/men/2.jpg',
      },
    ]"
  >
    <template v-slot:tag="{ option, handleTagRemove, disabled }">
      <div class="multiselect-tag is-user">
        <img :src="option.image" />
        {{ option.name }}
        <i
          v-if="!disabled"
          @click.prevent
          @mousedown.prevent.stop="handleTagRemove(option, $event)"
        />
      </div>
    </template>
    <template v-slot:option="{ option }">
      <img class="character-option-icon" :src="option.image" />
      {{ option.name }}
    </template>
  </Multiselect>
----
![image](https://user-images.githubusercontent.com/40855265/114036201-293c8500-9880-11eb-983b-7fa0d71d57ac.png)
![image](https://user-images.githubusercontent.com/40855265/114036240-30fc2980-9880-11eb-8424-d6fa1dccc21e.png)
![image](https://user-images.githubusercontent.com/40855265/114036282-3b1e2800-9880-11eb-823a-2ac8c1133d94.png)
![image](https://user-images.githubusercontent.com/40855265/114036330-45d8bd00-9880-11eb-9fbf-f445499b7f3a.png)

**Comment by adamberecz** [comment]
Please update to `1.5.0`. If the issue still persist please create a reproducible example or screenshots to help me understand the issue.
