### ISSUE TITLE
Improving doc with multiple selects that depend each other

### ISSUE THREAD

**Issue by realnot** [vueform/multiselect#60]
Hi, I have a suggestion that may improve the docs providing an example / use case where there are multiple select that depends each other. This is the case of **Country**, **Zone**, **Region**, **Province**, **City**, where for example when I select a **Region**, I want that Province and **City** are filtered to become a subset of **Region** and also the reverse case, when a **City** is selected, the **Province**, **Region**, **Zone** and **Country** are automatically selected / filled.

**Comment by adamberecz** [comment]
This really depends on your use case. There are many ways to achieve this. Here's a simple one with computed props:

``` vue
<template>
  <form>
    <Multiselect
      v-model="selectedCountry"
      :options="countries"
      ref="country"
    ></Multiselect>

    <Multiselect
      v-model="selectedCity"
      :options="cities"
      ref="city"
    ></Multiselect>
  </form>
</template>

<script>
import Multiselect from '@vueform/multiselect/src/Multiselect'

export default {
  components: {
    Multiselect,
  },
  data() {
    return {
      countries: {
        us: 'United States',
        de: 'Germany'
      },
      selectedCountry: null,
      selectedCity: null,
    };
  },
  watch: {
    selectedCountry() {
      this.selectedCity = null
    }
  },
  computed: {
    cities() {
      const cities = {
        us: ['Philadelphia', 'Detroit'],
        de: ['Berlin', 'Stuttgart'],
      }

      if (!this.selectedCountry) {
        return []
      }

      return cities[this.selectedCountry]
    }
  },
};
</script>

<style src="@vueform/multiselect/themes/default.css"></style>
```

You might also rely on `@change` event or event async options in different implementations.
