### ISSUE TITLE
Multiselect-clear element should not be rendered when canDeselect is set

### ISSUE THREAD

**Issue by LemarinelNet** [vueform/multiselect#61]
### Version

* Vue version: 3

### Description

I've setup the multiselect in single mode, with canDeselect set to FALSE.
When the item is selected, the "cross button" on the right side of the list still appears, and that's confusing. 
I think this cross button should not be rendered, perhaps modifiing the `v-if` part and adding `&& canDeselect`

Thanks for your feedback

**Comment by adamberecz** [comment]
Thanks @BKirev for the PR I've added it with tests in `1.5.0`.

**Comment by douglasmanzelmann** [comment]
@adamberecz It's possible I'm doing something incorrect here, but this still isn't working with Vue3 and `1.5.0`.

```
          <Multiselect
            v-if="hasAccess"
            v-model="selectedCustomerId"
            :options="customerIds"
            canDeselect="false" />
```
I've attempted with `can-deselect="false"` as well.

**Comment by adamberecz** [comment]
Try `:canDeselect="false"` (starts with `:`)

**Comment by douglasmanzelmann** [comment]
@adamberecz I'm an idiot. Thank you. I appreciate the quick response.
