### ISSUE TITLE
InternalValue sometimes empty when page refresh

### ISSUE THREAD

**Issue by ashafizullah** [vueform/multiselect#62]
Use vue 3 with multiselect, i have an problem with InternalValue sometimes return empty when page refresh. When i go to another page, and return, sometimes the InternalValue is success. I get a data from server, and store it on reactivity. 

`<multiselect v-model="company.city" :options="listCity.data" valueProp="_id" label="name" trackBy="name" :searchable="true" placeholder="Choose city:" />`

SETUP():
`const company = reactive({
            city: '',
})`

`const listCity = reactive({
            data: []
})`

`onMounted(() => {
            axios.get("city").then((response) => {
                listCity.data = response.data
            }).catch(error => {
                console.log(error);
            })
        })`

Thank for your help.

**Comment by MrEduar** [comment]
Hello @ashafizullah, were you able to solve this problem? I have a similar problem.

**Comment by ashafizullah** [comment]
No, my problem not solved yet

**Comment by adamberecz** [comment]
Please use the issue template to create a reproducible example:
https://jsfiddle.net/q6Lnpr7a/
