### ISSUE TITLE
How to get a selected item all data(id,name,username,others)? 

### ISSUE THREAD

**Issue by raju10281** [vueform/multiselect#63]
Here is JSfiddle,
[jsfiddle](https://jsfiddle.net/7epowq9v/1/)

Is there better way to do get it corresponding data?

**Comment by adamberecz** [comment]
Simply use `@select="onchange"` and you should have the full option object as the first param:
``` js
methods:{
  onchange(option){
    this.selected_row = option;
  }
}
```

**Comment by raju10281** [comment]
> Simply use `@select="onchange"` and you should have the full option object as the first param:
> 
> ```js
> methods:{
>   onchange(option){
>     this.selected_row = option;
>   }
> }
> ```

Hi adamberecz,

No, it's not returning the selected row.
option is containing only selected value.

**Comment by yogesh-gohil** [comment]
you can get object data in the v-model itself by passing **:object="true"** props to multiselect
