### ISSUE TITLE
I could really use a specific example about how to detect that something is selected. 

### ISSUE THREAD

**Issue by geewhizbang** [vueform/multiselect#64]
The documentation mentions @select to handle a selection event. I have this in template:

    <Multiselect v-model="data.scriptsSelected" mode="tags" placeholder="Scripts"
          :options="data.scriptsFiltered" ref="scripts" @select="scriptChange($event)"
          :maxHeight="data.maxHeight" id="scriptMultiselect" />

And in methods:

     scriptChange: function($event) {
         console.log("Event:" + JSON.stringify($event, null, '  '));
         this.data.scriptsSelected.forEach(id => function() {
           if (this.data.scriptOrder.indexOf(id) < 0) {
             this.data.scriptOrder.push(id);
           }
         });
         console.log("scriptOrder:" + JSON.stringify(this.data.scriptOrder, null, '  '));
      },
      
For some reason this.data.scriptsSelected doesn't loop and this code doesn't work. The dom object contained in $event isn't terribly useful.

If you could provide at least one example of how this works, it would be great.

**Comment by adamberecz** [comment]
Using `@select="scriptChange"` would give you `scriptChange: function(selectedOption)` that could be more useful. Though we don't know any specifics. The `select` event should work, so the issue must be somewhere else in your code.
