### ISSUE TITLE
How to load async options only when open select

### ISSUE THREAD

**Issue by arthurlauck** [vueform/multiselect#67]
I'm wondering if there is a way, to just load the options as a function callback, when the user click in the select, the reason for that, is to spare a request when the user dont want to add or change that select input.

I see the "resolveOnLoad" option, but if false, when the callback is called?

Is there a way to do that?

**Comment by adamberecz** [comment]
You might set `resolveOnLoad` to `false` and listen to `open` event to call `refreshOptions`.

**Comment by arthurlauck** [comment]
So I need to handle in my own component?

Like, creating a flag, that shows that the options was or not loaded and then controlling the `open` event (to not refreshOptins twice, every time the user open the select)?

Wouldnt it be interesting to have this in the core of the multiselect component?

**Comment by adamberecz** [comment]
That's actually easy to achieve without the flag, you just need a ref to Multiselect and check `resolvedOptions` property - if it's empty you need to load them on open.

I'd rather keep the library small at this point and leave these minor nice features up to the user as long as they are easy to implement.

**Comment by arthurlauck** [comment]
@adamberecz Make sense, thanks for the attention!

I will implement it in my code, maybe after that we could put as an example?
