### ISSUE TITLE
beforelist slot doesn't allow focus on elements like input

### ISSUE THREAD

**Issue by richardbaltariu** [vueform/multiselect#71]
### Version

* Vue version: 3

### Description

Components like `input` inside `beforelist` slot are not focusable because when clicking the input (or component), the dropdown list with options goes away. One example use case for this, would be adding the search input inside the list.

### Demo

See example 1
https://jsfiddle.net/fr67gpke/

**Comment by richardbaltariu** [comment]
Any news here?

**Comment by adamberecz** [comment]
Yep @richardbaltariu - you should be able to do this from `2.0.0`.
