### ISSUE TITLE
Caret missing when a item is selected

### ISSUE THREAD

**Issue by naftis** [vueform/multiselect#74]
I noticed that https://github.com/vueform/multiselect/commit/d0114290009c99a659c9f68cb68704aea243ae7b this commit hides the caret when a item is selected. My multiselect has always a selected value as it's a Sort by -menu.

I'm not sure if hiding the caret when item is selected is the best default. The native HTML dropdown has it always visible, and I think it might easily get confused to a textbox if the caret's missing.

**Possible solutions:**

1) Have the caret always visible by default; with a setting to hide it on select.
2) Hide the caret when item is selected by default; with a setting to always have it visible.

If you're busy, I think I can try to create a PR for this, if we decide the preferred way to go.

**Comment by mseele** [comment]
As workaround you can add a caret via the caret & the clear slot. This is how we did it.

**Comment by mseele** [comment]
i've created a pull request as possible solution for this issue: https://github.com/vueform/multiselect/pull/77

**Comment by Rekryt** [comment]
@mseele
temp fix for this promblem:
```vue
<template><Multiselect v-bind="$attrs" /></template>
<script>
import Multiselect from '@vueform/multiselect';

export default {
    components: { Multiselect },
    mounted() {
        this.$el
            .querySelector('.multiselect-input')
            .insertAdjacentHTML('beforeend', '<span class="multiselect-caret"></span>');
    },
};
</script>
```

**Comment by adamberecz** [comment]
Caret is now always visible when `caret: true`.
