### ISSUE TITLE
Enter click opens all other instances popups

### ISSUE THREAD

**Issue by mseele** [vueform/multiselect#75]
### Version

* Vue version: 3

### Description

When i click enter in one of the multiselect instances, all other instances popups will open

How to reproduce:
- Clone https://github.com/mseele/multiselect-enter-issue & run
- Click into first instance
- Popup opens and pre-selects Batman
- Click Enter
- Batman is selected in the first instance
- The Popup of the second instance is opend **BUG**

### Demo

https://github.com/mseele/multiselect-enter-issue

**Comment by mseele** [comment]
And a example in jsfiddle: https://jsfiddle.net/mseele/eta7fq9u/

**Comment by mseele** [comment]
I've investigated a little bit deeper:
The Enter click fires focus Events for "all" instances (for whatever reason). The Bug only happens under Chrome & Firefox, Edge (Chromium) does not fire these "wrong" Focus Events. Interesting of that the `explicitOriginalTarget` Property in Firefox points always to the "selected" instance.

A workaround is to add a onfocus-wrapper and skip these "wrong focus events" by checking the `relatedTarget` event property (only exist on FocusEvent and the "wrong focus events" are only Event instances):

```
function onFocus(event) {
  if (typeof event.relatedTarget === 'undefined') {
    return
  }
  dropdown.openDropdown()
}
```
This works for me but feels really like a dirty hack

**Comment by adamberecz** [comment]
@mseele this should be fine from `2.0.0`
