### ISSUE TITLE
Open tag should be added on blur. Also add comma and semicolon as triggers.

### ISSUE THREAD

**Issue by alesf** [vueform/multiselect#79]
When in tag mode and with show options set to false tags are added with addTagOn space/enter but if you blue the input the last tag is not added. You need to use space/enter.

It would also be great if you could add characters as comma and semicolon as triggers for adding.

You can test this here:
https://jsfiddle.net/p3hgr7ty/2/

**Comment by adamberecz** [comment]
Added `,` and `;` options for `addTagOn`.

**Comment by Grawl** [comment]
What about adding tag on focus lost? It's not cool when I type text into field, press Tab to go to another field and I lost my text in previous field.

**Comment by alesf** [comment]
In my fork I added this to [multiselect/src/composables/useSearch.js](https://github.com/alesf/multiselect/blob/7416bdf38d1acfa4032f45e08b275921d9d34b53/src/composables/useSearch.js):

```js
const selectPointer = dep.selectPointer

...

const blurSearch = () => {
    if (!searchable.value) {
      return
    }

    selectPointer()
    input.value.blur()
  }
```

@adamberecz is this an acceptable solution?

**Comment by Grawl** [comment]
I think it must be an option via prop
