### ISSUE TITLE
Default value not displayed when using async options

### ISSUE THREAD

**Issue by seanwuapps** [vueform/multiselect#80]
### Version

* Vue version: 3

### Description

When used in async mode (async function as options), the default `v-model` is not displayed but available as value.

### Demo

https://jsfiddle.net/szm21chq/
See example #5 (only diff from [the original JSFiddle template](https://jsfiddle.net/q6Lnpr7a/) is the added `value`)

**Comment by adamberecz** [comment]
That's because `'Java'` as an option does not exist. If you need default value without using `resolveOnLoad` you can use `object: true`and provide the default value as an object: `{ value: 'Java', label: 'Java' }`
