### ISSUE TITLE
There is a bug where the following contents are changed when selecting options of mutiselect.

### ISSUE THREAD

**Issue by l22sangdlf** [vueform/multiselect#81]
### Version

* Vue version: 
3.1.0-beta.7

### Description

When multiselect is selected, the following options are changed. Attach an image.

![multiselect](https://user-images.githubusercontent.com/52414300/120996940-bf7a2200-c7c1-11eb-80b1-deaf76d59195.png)
### Demo

Please use our [JSFiddle template](https://jsfiddle.net/q6Lnpr7a/) to reproduce the bug. Issues without working reproduction might be ignored.

**Comment by adamberecz** [comment]
Feel free to reopen with a reproducible example. https://jsfiddle.net/g56vfpe4/
