### ISSUE TITLE
CSP compliance: Remove inline styles

### ISSUE THREAD

**Issue by carlobeltrame** [vueform/multiselect#84]
Hi! Thanks for this component, I have used it successfully in a small project. Now I have another project that has a strict CSP policy that disallows inline CSS styles, such as the ones that are added using a `style="..."` attribute. In this project, I'd like to replace  shentao/vue-multiselect with your multiselect library.

There are three uses of such inline styles in Multiselect.vue, which prevent me from using it currently:
1. https://github.com/vueform/multiselect/blob/main/src/Multiselect.vue#L98 for setting the width of the search input based on the amount of characters entered, falling back to 100% width in tags mode
2. https://github.com/vueform/multiselect/blob/main/src/Multiselect.vue#L84 same on the div wrapping the input
3. https://github.com/vueform/multiselect/blob/main/src/Multiselect.vue#L136 for setting the maxHeight of the options dropdown using a prop

The first can be replaced with a `v-if` to handle tags mode, plus using the CSP-safe `size` attribute on the input field. The second one can be replaced by leveraging the auto-sizing capabilities of CSS on the wrapping div, so that the width automatically matches the width of the div's content.
The third one I think can't directly be made CSP-safe, but I struggle to see why `maxHeight` needs to be a prop at all, when users of the library can easily add their preferred max-height using their own CSS when using the multiselect component: `<style scoped>.multiselect-options { max-height: whatever I need }</style>`. Users that don't have CSP constraints can even set it dynamically if they really ever need to. In case you're worried about the breaking change, I (and the CSP constraint) would also be satisfied if the `style` attribute was left out in case one doesn't use the `max-height=""` prop.

I'd be happy to provide a pull request to implement this. Would you be interested in such a change?

**Comment by adamberecz** [comment]
With `2.0.0` we now only have `maxHeight` and the width of the input search when using tags. The `maxHeight` is definitely doable as you've mentioned (skipping the attribute when undefined) but the tags input search is trickier. Does CSP allows adding style attribute **after** the page is loaded?

**Comment by carlobeltrame** [comment]
Unfortunately no, CSP can either completely allow or completely disallow any `style` attributes. See [this excellent talk](https://www.youtube.com/watch?v=eb3suf4REyI) on why inline styles are even considered a risk in the first place, and this applies to both styles at page load as well as styles added after page load.

The input field width could maybe be implemented by overlaying an invisible copy of the input content and have the input match that width. I'll try to construct a fiddle to demonstrate what I mean.

Anyways, for calculating the real input width you now use some more inline styles in `2.0.0`: In https://github.com/vueform/multiselect/blob/947a961ceef48c76e0c851b01bddc6573c4be8fa/src/composables/useSearch.js#L35 you have created an offscreen span to calculate the text width of the search text. These inline styles are fixed, and could be easily replaced with a CSS class to make it CSP compliant (but if my proposal with the overlay works this calculation would be obsolete anyways).

**Comment by carlobeltrame** [comment]
Here you go: https://jsfiddle.net/y6jnkomq/67/
Almost no JavaScript and definitely no inline `style` attributes needed to make the input's width adapt to the text typed into it.

**Comment by adamberecz** [comment]
Thanks for the implementation @carlobeltrame - seems fine on the first look! I've signed this up for the next release.

**Comment by adamberecz** [comment]
This got implemented `2.1.0` - I believe no inline styles left. Thanks for the detailed solution.

**Comment by carlobeltrame** [comment]
I can confirm that, thanks for the fix!
