### ISSUE TITLE
Transform or validate a new tag before is added

### ISSUE THREAD

**Issue by antoniogiroz** [vueform/multiselect#86]
Hi,

How can I transform an added tag (for instance, transforming to uppercase) or validate it to prevent will be added.

Thanks!

**Comment by bouffekai** [comment]
Up ! How can we validate a tag before it added ? Like regex matching for example

**Comment by andersonalvesalmeida** [comment]
I have de same question!!!

**Comment by adamberecz** [comment]
@antoniogiroz @bouffekai @andersonalvesalmeida - added `onCreate` option in `2.4.0`, here's how you can use it:
https://github.com/vueform/multiselect#manage-created-tag-asynchronously
