### ISSUE TITLE
Feature Request: Close menu on select container click

### ISSUE THREAD

**Issue by ayZagen** [vueform/multiselect#87]
Ability/option to close select menu while it is open when clicked on select container.

For reference, in the state below when we click to the `1 option selected` or anywhere in the select container the menu should be closed.
![image](https://user-images.githubusercontent.com/11196940/123136333-7ed60600-d45b-11eb-910d-a782f0583cc5.png)

**Comment by adamberecz** [comment]
Couldn't achieve this, all I could do was to close on caret https://github.com/vueform/multiselect/issues/88.
