### ISSUE TITLE
Unable to get options from async/await

### ISSUE THREAD

**Issue by laics1984** [vueform/multiselect#89]
### Version

* Vue version: 3

I am trying to fetch options value with async/await. However, received the error message:
![image](https://user-images.githubusercontent.com/1420247/124051152-88a8cc00-da4e-11eb-9cc0-d52402a72103.png)

Below is how I use to fetch option:

```
<Multiselect
      :placeholder="placeholder"
      :options="getOptions()"
      mode="single"
      :canDeselect="canDeselect"
      @change="makeSelection"
      v-model="selected"
      :noOptionsText="noOptionsText"
      @close="closeSelection"
      :resolveOnLoad="false"
      :clearOnSelect="true"
      @select="$emit('update:modelValue', selected);"
      @clear="$emit('clear-selection')"
      ref="selectRef"
      :disabled="disabled"
    />
```

in setup:
```
  const getOptions = async () => {
    const namespacesList = await utils.listToLink(prop);
    console.log(namespacesList)
    return namespacesList;
  };
```

I am able to console.log the values, thus the async/awaits function did return a list
![image](https://user-images.githubusercontent.com/1420247/124051575-5055bd80-da4f-11eb-9da0-d0c065106b43.png)

Please advice. Thanks

**Comment by kikusmartaos** [comment]
You should do :options="async function(query) { return await getOptions(query) }"

**Comment by laics1984** [comment]
> You should write:
> `:options="async function(query) { return await getOptions(query) }"`

What is the purpose of `query`?

**Comment by kikusmartaos** [comment]
I think in your case `query` is not necessary, in my case `query` is the input value when I search inside Multiselect.

**Comment by adamberecz** [comment]
`:options="getOptions"` should do the trick. We need to reference the fetch method, not calling it.
