### ISSUE TITLE
Slots data and props naming convention

### ISSUE THREAD

**Issue by IsraelOrtuno** [vueform/multiselect#93]
It would be cool to have a more standard naming for slot vars and props. Just an example:

#### singlelabel slot
``` value ```

#### option slot
``` option ```

Following vuetify's example, my proposal is to standarize all these "value/option/whatever" variables into a more generic one called `item` so it'll be way easier to remember and deal with slots:

```vue
<template #singlelabel="{ item }">{{ item.title }}</template>
<template #option="{ item }">{{ item.title }}</template>

// instead of

<template #singlelabel="{ value }">{{ value.title }}</template>
<template #option="{ option }">{{ option.title }}</template>
```

Also some props could also be standarized:

- value-prop by  `item-value` / `item-key`
- label => `item-label` / `item-text`

I am aware that this would introduce some breaking changes and that may not be desirable with v2 just released, but it'd be way easier to use the component and less go and back from docs.

The proposal of this issue is just to open the debate and consider a future PR if looks like a good idea.

**Comment by adamberecz** [comment]
The `value` carries extra information that it's the actually selected **value**, while `item` is just general one that "could be" any of the items (when read without active thinking).

I'm up for naming variables developer friendly, but in this case I think `value` has a more precise meaning which should be a stronger point than comfort (on my scale).

(I've actually added `:item` as an extra prop to the 4 slots then realized this when I started tweaking the docs.)
