### ISSUE TITLE
Help with debugging build error

### ISSUE THREAD

**Issue by jpobley** [vueform/multiselect#94]
I'm trying to generate a static site with NuxtJS and am running into a build error that I can't figure out:

```bash
ERROR in ./src/components/sharing/Share.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--3-oneOf-1-2!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/sharing/Share.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) postcss-custom-properties: <css input> Unknown word

> 1 | var(--ms-border-width, 1px)*2 + var(--ms-font-size, 1rem)*var(--ms-line-height, 1.375) + var(--ms-py, .5rem)*2
    | ^
```

**Things that do work**:
1. I run `nuxt` during development and haven't had any problems with building, hot-reloading, etc. Everything works as expected.
2. If I remove [the offending line](https://github.com/vueform/multiselect/blob/main/themes/default.scss#L15) from `node_modules/@vueform/multiselect/themes/default.scss`, then everything works just fine.  Obviously, this isn't a solution, but I can't understand what I've incorrectly configured that throws an error for just that one line.

Thinking that maybe I had the wrong incantation of loaders, I did a fresh app with `npm init nuxt-app@latest foo` and pushed the repo up [here](https://github.com/jpobley/multiselect-error-example). The error still occurs if you want to see it for yourself.

**Steps to reproduce:**
1. `git clone git@github.com:jpobley/multiselect-error-example.git`
2. `cd multiselect-error-example`
3. `npm install`
4. `npm run dev` (go to http://localhost:3000 to see it working just fine)
5. `npm run build` (error)

If you have any ideas on what I'm missing, I'd love to hear them!

**Comment by anh-collab** [comment]
@jpobley don't know if you still need it, but I was able to bypass that error by adding the css/scss import to the `css: []` section of the `nuxt.config.js` file instead.
