### ISSUE TITLE
Vue3 cannot deselect when using multiple

### ISSUE THREAD

**Issue by ngoccuongyb92** [vueform/multiselect#95]
![image](https://user-images.githubusercontent.com/69663965/125886314-ba6f3dc9-32b7-440f-9c34-d829750e2be1.png)

![image](https://user-images.githubusercontent.com/69663965/125886662-a72b6b17-d9e0-431d-9e73-6fe6f7bf65fe.png)

I use Asynchronous select to get the data but when I want to delete the selected data it cannot, please help

**Comment by adamberecz** [comment]
Feel free to reopen with a reproducible example. https://jsfiddle.net/g56vfpe4/

**Comment by greendesertsnow** [comment]
I was having a similar problem with version 1.5.0.
I had more than one components that the user supposed not to be able to deselect. And I could achieve that functionality with only one component. 
Now that I've upgraded to the version 2.1.2, the feature is working just fine.
I need to adjust the css though.
