### ISSUE TITLE
Free-typed tags not working

### ISSUE THREAD

**Issue by andresespinosapc** [vueform/multiselect#96]
### Version

* Vue version: 3

### Description

I'm trying to use free-typed tags. I want to just write text, write a comma and I want the tag to be added, without showing any dropdown. But when I set `showOptions` to `false`, when I type any of the keys on the `addTagOn` option nothing happens.

### Demo

https://jsfiddle.net/andresespinosapc/5omr6cxj/12/

**Comment by Uninen** [comment]
I bumped into this same issue. I have exactly the same use case; I just want to have a simple input with ability add free tags separated by comma or enter.

When setting `showOptions` to false, no new tags can be created anymore.

**Comment by adamberecz** [comment]
Fixed in `2.1.0`.
