### ISSUE TITLE
Vue 3 + ts: `composition-api`-module cannot be found.

### ISSUE THREAD

**Issue by zergar** [vueform/multiselect#97]
### Version

* Vue version: 3
* With TypeScript-Addon

### Description

When importing `Multiselect`, Vue states, that the `composition-api`-module cannot be found.

The following error is displayed:
```
Failed to compile.

./node_modules/@vueform/multiselect/src/composables/useData.js
Module not found: Error: Can't resolve 'composition-api' in '/home/user/dir/multiselect-bug/node_modules/@vueform/multiselect/src/composables'
```

I've poked a bit in the lib-code, and changing the imports from `components-api` to `vue` does indeed solve the issue. I can create a pull-request, but I'm unsure whether this would destroy anything else in the process, so I'd like to ask here first.

### Demo

https://github.com/zergar/vueforms-multiselect-bug

**Comment by PeterEsenwa** [comment]
I have encountered this same issue. I created a patch (on v1.5.0) and added it as an npm `postinstall` script until it is fixed

**Comment by mp3000mp** [comment]
Hi, I had the same issue but changing
`import Multiselect from '@vueform/multiselect/src/Multiselect'`
to
`import Multiselect from '@vueform/multiselect'`
fixed it on my side.

**Comment by adamberecz** [comment]
Yep, the thing is that 'composition-api' is a general name (not an actual library), which gets replaced by `@vue/composition-api` in Vue 2 or `vue` in Vue 3 when creating the `dist` bundle. If you need to use the `src` version, you might create an alias to `composition-api` in your bundler.
